/* This file is public domain */

#ifndef _JPILS_OPENGL_H_
#define _JPILS_OPENGL_H_

#include "pils-kernel/writing.h"
#include <juce.h>

BEGIN_JUCE_NAMESPACE

class OpenGL
{
public:
	OpenGL() {}
    static void gl__Accum (unsigned int op, float value);
    static void gl__AlphaFunc (unsigned int func, float ref);
//    static bool gl__AreTexturesResident (int n, const unsigned int * textures, unsigned char * residences);
    static void gl__ArrayElement (int i);
    static void gl__Begin (unsigned int mode);
    static void gl__BindTexture (unsigned int target, unsigned int texture);
//    static void gl__Bitmap (int width, int height, float xorig, float yorig, float xmove, float ymove, const unsigned char * bitmap);
    static void gl__BlendFunc (unsigned int sfactor, unsigned int dfactor);
    static void gl__CallList (unsigned int list);
    static void gl__CallLists (int n, unsigned int type, const void * lists);
    static void gl__Clear (unsigned int mask);
    static void gl__ClearAccum (float red, float green, float blue, float alpha);
    static void gl__ClearColor (float red, float green, float blue, float alpha);
    static void gl__ClearDepth (double depth);
    static void gl__ClearIndex (float c);
    static void gl__ClearStencil (int s);
//    static void gl__ClipPlane (unsigned int plane, const double * equation);
//    static void gl__Color3b (signed char red, signed char green, signed char blue);
//    static void gl__Color3bv (const signed char * v);
    static void gl__Color__3d (double red, double green, double blue);
//    static void gl__Color3dv (const double * v);
//    static void gl__Color3f (float red, float green, float blue);
//    static void gl__Color3fv (const float * v);
//    static void gl__Color3i (int red, int green, int blue);
//    static void gl__Color3iv (const int * v);
//    static void gl__Color3s (short red, short green, short blue);
//    static void gl__Color3sv (const short * v);
//    static void gl__Color3ub (unsigned char red, unsigned char green, unsigned char blue);
//    static void gl__Color3ubv (const unsigned char * v);
//    static void gl__Color3ui (unsigned int red, unsigned int green, unsigned int blue);
//    static void gl__Color3uiv (const unsigned int * v);
//    static void gl__Color3us (unsigned short red, unsigned short green, unsigned short blue);
//    static void gl__Color3usv (const unsigned short * v);
//    static void gl__Color4b (signed char red, signed char green, signed char blue, signed char alpha);
//    static void gl__Color4bv (const signed char * v);
    static void gl__Color__4d (double red, double green, double blue, double alpha);
//    static void gl__Color4dv (const double * v);
//    static void gl__Color4f (float red, float green, float blue, float alpha);
//    static void gl__Color4fv (const float * v);
//    static void gl__Color4i (int red, int green, int blue, int alpha);
//    static void gl__Color4iv (const int * v);
//    static void gl__Color4s (short red, short green, short blue, short alpha);
//    static void gl__Color4sv (const short * v);
//    static void gl__Color4ub (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
//    static void gl__Color4ubv (const unsigned char * v);
//    static void gl__Color4ui (unsigned int red, unsigned int green, unsigned int blue, unsigned int alpha);
//    static void gl__Color4uiv (const unsigned int * v);
//    static void gl__Color4us (unsigned short red, unsigned short green, unsigned short blue, unsigned short alpha);
//    static void gl__Color4usv (const unsigned short * v);
    static void gl__ColorMask (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
    static void gl__ColorMaterial (unsigned int face, unsigned int mode);
    static void gl__ColorPointer (int size, unsigned int type, int stride, const void * pointer);
    static void gl__CopyPixels (int x, int y, int width, int height, unsigned int type);
    static void gl__CopyTexImage1D (unsigned int target, int level, unsigned int internalFormat, int x, int y, int width, int border);
    static void gl__CopyTexImage2D (unsigned int target, int level, unsigned int internalFormat, int x, int y, int width, int height, int border);
    static void gl__CopyTexSubImage1D (unsigned int target, int level, int xoffset, int x, int y, int width);
    static void gl__CopyTexSubImage2D (unsigned int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
    static void gl__CullFace (unsigned int mode);
    static void gl__DeleteLists (unsigned int list, int range);
//    static void gl__DeleteTextures (int n, const unsigned int * textures);
    static void gl__DepthFunc (unsigned int func);
    static void gl__DepthMask (unsigned char flag);
    static void gl__DepthRange (double zNear, double zFar);
    static void gl__Disable (unsigned int cap);
    static void gl__DisableClientState (unsigned int array);
    static void gl__DrawArrays (unsigned int mode, int first, int count);
    static void gl__DrawBuffer (unsigned int mode);
    static void gl__DrawElements (unsigned int mode, int count, unsigned int type, const void * indices);
    static void gl__DrawPixels (int width, int height, unsigned int format, unsigned int type, const void * pixels);
    static void gl__EdgeFlag (unsigned char flag);
    static void gl__EdgeFlagPointer (int stride, const void * pointer);
    static void gl__EdgeFlagv (const unsigned char * flag);
    static void gl__Enable (unsigned int cap);
    static void gl__EnableClientState (unsigned int array);
    static void gl__End ();
    static void gl__EndList ();
    static void gl__EvalCoord__1d (double u);
//    static void gl__EvalCoord1dv (const double * u);
//    static void gl__EvalCoord1f (float u);
//    static void gl__EvalCoord1fv (const float * u);
    static void gl__EvalCoord__2d (double u, double v);
//    static void gl__EvalCoord2dv (const double * u);
//    static void gl__EvalCoord2f (float u, float v);
//    static void gl__EvalCoord2fv (const float * u);
    static void gl__EvalMesh__1 (unsigned int mode, int i1, int i2);
    static void gl__EvalMesh__2 (unsigned int mode, int i1, int i2, int j1, int j2);
    static void gl__EvalPoint__1 (int i);
    static void gl__EvalPoint__2 (int i, int j);
//    static void gl__FeedbackBuffer (int size, unsigned int type, float * buffer);
    static void gl__Finish ();
    static void gl__Flush ();
    static void gl__Fog__f (unsigned int pname, float param);
//    static void gl__Fogfv (unsigned int pname, const float * params);
//    static void gl__Fogi (unsigned int pname, int param);
//    static void gl__Fogiv (unsigned int pname, const int * params);
    static void gl__FrontFace (unsigned int mode);
    static void gl__Frustum (double left, double right, double bottom, double top, double zNear, double zFar);
    static unsigned int gl__GenLists (int range);
//    static void gl__GenTextures (int n, unsigned int * textures);
//    static void gl__GetBooleanv (unsigned int pname, unsigned char * params);
//    static void gl__GetClipPlane (unsigned int plane, double * equation);
//    static void gl__GetDoublev (unsigned int pname, double * params);
    static unsigned int gl__GetError ();
//    static void gl__GetFloatv (unsigned int pname, float * params);
//    static void gl__GetIntegerv (unsigned int pname, int * params);
//    static void gl__GetLightfv (unsigned int light, unsigned int pname, float * params);
//    static void gl__GetLightiv (unsigned int light, unsigned int pname, int * params);
//    static void gl__GetMapdv (unsigned int target, unsigned int query, double * v);
//    static void gl__GetMapfv (unsigned int target, unsigned int query, float * v);
//    static void gl__GetMapiv (unsigned int target, unsigned int query, int * v);
//    static void gl__GetMaterialfv (unsigned int face, unsigned int pname, float * params);
//    static void gl__GetMaterialiv (unsigned int face, unsigned int pname, int * params);
//    static void gl__GetPixelMapfv (unsigned int map, float * values);
//    static void gl__GetPixelMapuiv (unsigned int map, unsigned int * values);
//    static void gl__GetPixelMapusv (unsigned int map, unsigned short * values);
//    static void gl__GetPointerv (unsigned int pname, void* * params);
//    static void gl__GetPolygonStipple (unsigned char * mask);
    static const unsigned char * gl__GetString (unsigned int name);
//    static void gl__GetTexEnvfv (unsigned int target, unsigned int pname, float * params);
//    static void gl__GetTexEnviv (unsigned int target, unsigned int pname, int * params);
//    static void gl__GetTexGendv (unsigned int coord, unsigned int pname, double * params);
//    static void gl__GetTexGenfv (unsigned int coord, unsigned int pname, float * params);
//    static void gl__GetTexGeniv (unsigned int coord, unsigned int pname, int * params);
    static void gl__GetTexImage (unsigned int target, int level, unsigned int format, unsigned int type, void * pixels);
//    static void gl__GetTexLevelParameterfv (unsigned int target, int level, unsigned int pname, float * params);
//    static void gl__GetTexLevelParameteriv (unsigned int target, int level, unsigned int pname, int * params);
//    static void gl__GetTexParameterfv (unsigned int target, unsigned int pname, float * params);
//    static void gl__GetTexParameteriv (unsigned int target, unsigned int pname, int * params);
    static void gl__Hint (unsigned int target, unsigned int mode);
    static void gl__IndexMask (unsigned int mask);
    static void gl__IndexPointer (unsigned int type, int stride, const void * pointer);
    static void gl__Index__d (double c);
//    static void gl__Indexdv (const double * c);
//    static void gl__Indexf (float c);
//    static void gl__Indexfv (const float * c);
//    static void gl__Indexi (int c);
//    static void gl__Indexiv (const int * c);
//    static void gl__Indexs (short c);
//    static void gl__Indexsv (const short * c);
//    static void gl__Indexub (unsigned char c);
//    static void gl__Indexubv (const unsigned char * c);
    static void gl__InitNames ();
    static void gl__InterleavedArrays (unsigned int format, int stride, const void * pointer);
    static bool gl__IsEnabled (unsigned int cap);
    static bool gl__IsList (unsigned int list);
    static bool gl__IsTexture (unsigned int texture);
    static void gl__LightModel__f (unsigned int pname, float param);
//    static void gl__LightModelfv (unsigned int pname, const float * params);
//    static void gl__LightModeli (unsigned int pname, int param);
//    static void gl__LightModeliv (unsigned int pname, const int * params);
    static void gl__Light__f (unsigned int light, unsigned int pname, float param);
//    static void gl__Lightfv (unsigned int light, unsigned int pname, const float * params);
//    static void gl__Lighti (unsigned int light, unsigned int pname, int param);
//    static void gl__Lightiv (unsigned int light, unsigned int pname, const int * params);
//    static void gl__LineStipple (int factor, unsigned short pattern);
    static void gl__LineWidth (float width);
    static void gl__ListBase (unsigned int base);
    static void gl__LoadIdentity ();
//    static void gl__LoadMatrixd (const double * m);
//    static void gl__LoadMatrixf (const float * m);
    static void gl__LoadName (unsigned int name);
    static void gl__LogicOp (unsigned int opcode);
//    static void gl__Map1d (unsigned int target, double u1, double u2, int stride, int order, const double * points);
//    static void gl__Map1f (unsigned int target, float u1, float u2, int stride, int order, const float * points);
//    static void gl__Map2d (unsigned int target, double u1, double u2, int ustride, int uorder, double v1, double v2, int vstride, int vorder, const double * points);
//    static void gl__Map2f (unsigned int target, float u1, float u2, int ustride, int uorder, float v1, float v2, int vstride, int vorder, const float * points);
    static void gl__MapGrid__1d (int un, double u1, double u2);
//    static void gl__MapGrid1f (int un, float u1, float u2);
    static void gl__MapGrid__2d (int un, double u1, double u2, int vn, double v1, double v2);
//    static void gl__MapGrid2f (int un, float u1, float u2, int vn, float v1, float v2);
    static void gl__Material__f (unsigned int face, unsigned int pname, float param);
//    static void gl__Materialfv (unsigned int face, unsigned int pname, const float * params);
//    static void gl__Materiali (unsigned int face, unsigned int pname, int param);
//    static void gl__Materialiv (unsigned int face, unsigned int pname, const int * params);
    static void gl__MatrixMode (unsigned int mode);
//    static void gl__MultMatrixd (const double * m);
//    static void gl__MultMatrixf (const float * m);
    static void gl__NewList (unsigned int list, unsigned int mode);
//    static void gl__Normal3b (signed char nx, signed char ny, signed char nz);
//    static void gl__Normal3bv (const signed char * v);
    static void gl__Normal__3d (double nx, double ny, double nz);
//    static void gl__Normal3dv (const double * v);
//    static void gl__Normal3f (float nx, float ny, float nz);
//    static void gl__Normal3fv (const float * v);
//    static void gl__Normal3i (int nx, int ny, int nz);
//    static void gl__Normal3iv (const int * v);
//    static void gl__Normal3s (short nx, short ny, short nz);
//    static void gl__Normal3sv (const short * v);
    static void gl__NormalPointer (unsigned int type, int stride, const void * pointer);
    static void gl__Ortho (double left, double right, double bottom, double top, double zNear, double zFar);
    static void gl__PassThrough (float token);
//    static void gl__PixelMapfv (unsigned int map, int mapsize, const float * values);
//    static void gl__PixelMapuiv (unsigned int map, int mapsize, const unsigned int * values);
//    static void gl__PixelMapusv (unsigned int map, int mapsize, const unsigned short * values);
    static void gl__PixelStore__f (unsigned int pname, float param);
//    static void gl__PixelStorei (unsigned int pname, int param);
    static void gl__PixelTransfer__f (unsigned int pname, float param);
//    static void gl__PixelTransferi (unsigned int pname, int param);
    static void gl__PixelZoom (float xfactor, float yfactor);
    static void gl__PointSize (float size);
    static void gl__PolygonMode (unsigned int face, unsigned int mode);
    static void gl__PolygonOffset (float factor, float units);
    static void gl__PolygonStipple (const unsigned char * mask);
    static void gl__PopAttrib ();
    static void gl__PopClientAttrib ();
    static void gl__PopMatrix ();
    static void gl__PopName ();
//    static void gl__PrioritizeTextures (int n, const unsigned int * textures, const float * priorities);
    static void gl__PushAttrib (unsigned int mask);
    static void gl__PushClientAttrib (unsigned int mask);
    static void gl__PushMatrix ();
    static void gl__PushName (unsigned int name);
    static void gl__RasterPos__2d (double x, double y);
//    static void gl__RasterPos2dv (const double * v);
//    static void gl__RasterPos2f (float x, float y);
//    static void gl__RasterPos2fv (const float * v);
//    static void gl__RasterPos2i (int x, int y);
//    static void gl__RasterPos2iv (const int * v);
//    static void gl__RasterPos2s (short x, short y);
//    static void gl__RasterPos2sv (const short * v);
    static void gl__RasterPos__3d (double x, double y, double z);
//    static void gl__RasterPos3dv (const double * v);
//    static void gl__RasterPos3f (float x, float y, float z);
//    static void gl__RasterPos3fv (const float * v);
//    static void gl__RasterPos3i (int x, int y, int z);
//    static void gl__RasterPos3iv (const int * v);
//    static void gl__RasterPos3s (short x, short y, short z);
//    static void gl__RasterPos3sv (const short * v);
    static void gl__RasterPos__4d (double x, double y, double z, double w);
//    static void gl__RasterPos4dv (const double * v);
//    static void gl__RasterPos4f (float x, float y, float z, float w);
//    static void gl__RasterPos4fv (const float * v);
//    static void gl__RasterPos4i (int x, int y, int z, int w);
//    static void gl__RasterPos4iv (const int * v);
//    static void gl__RasterPos4s (short x, short y, short z, short w);
//    static void gl__RasterPos4sv (const short * v);
    static void gl__ReadBuffer (unsigned int mode);
    static void gl__ReadPixels (int x, int y, int width, int height, unsigned int format, unsigned int type, void * pixels);
    static void gl__Rect__d (double x1, double y1, double x2, double y2);
//    static void gl__Rectdv (const double * v1, const double * v2);
//    static void gl__Rectf (float x1, float y1, float x2, float y2);
//    static void gl__Rectfv (const float * v1, const float * v2);
//    static void gl__Recti (int x1, int y1, int x2, int y2);
//    static void gl__Rectiv (const int * v1, const int * v2);
//    static void gl__Rects (short x1, short y1, short x2, short y2);
//    static void gl__Rectsv (const short * v1, const short * v2);
    static int gl__RenderMode (unsigned int mode);
    static void gl__Rotate__d (double angle, double x, double y, double z);
//    static void gl__Rotatef (float angle, float x, float y, float z);
    static void gl__Scale__d (double x, double y, double z);
//    static void gl__Scalef (float x, float y, float z);
    static void gl__Scissor (int x, int y, int width, int height);
//    static void gl__SelectBuffer (int size, unsigned int * buffer);
    static void gl__ShadeModel (unsigned int mode);
    static void gl__StencilFunc (unsigned int func, int ref, unsigned int mask);
    static void gl__StencilMask (unsigned int mask);
    static void gl__StencilOp (unsigned int fail, unsigned int zfail, unsigned int zpass);
    static void gl__TexCoord__1d (double s);
//    static void gl__TexCoord1dv (const double * v);
//    static void gl__TexCoord1f (float s);
//    static void gl__TexCoord1fv (const float * v);
//    static void gl__TexCoord1i (int s);
//    static void gl__TexCoord1iv (const int * v);
//    static void gl__TexCoord1s (short s);
//    static void gl__TexCoord1sv (const short * v);
    static void gl__TexCoord__2d (double s, double t);
//    static void gl__TexCoord2dv (const double * v);
//    static void gl__TexCoord2f (float s, float t);
//    static void gl__TexCoord2fv (const float * v);
//    static void gl__TexCoord2i (int s, int t);
//    static void gl__TexCoord2iv (const int * v);
//    static void gl__TexCoord2s (short s, short t);
//    static void gl__TexCoord2sv (const short * v);
    static void gl__TexCoord__3d (double s, double t, double r);
//    static void gl__TexCoord3dv (const double * v);
//    static void gl__TexCoord3f (float s, float t, float r);
//    static void gl__TexCoord3fv (const float * v);
//    static void gl__TexCoord3i (int s, int t, int r);
//    static void gl__TexCoord3iv (const int * v);
//    static void gl__TexCoord3s (short s, short t, short r);
//    static void gl__TexCoord3sv (const short * v);
    static void gl__TexCoord__4d (double s, double t, double r, double q);
//    static void gl__TexCoord4dv (const double * v);
//    static void gl__TexCoord4f (float s, float t, float r, float q);
//    static void gl__TexCoord4fv (const float * v);
//    static void gl__TexCoord4i (int s, int t, int r, int q);
//    static void gl__TexCoord4iv (const int * v);
//    static void gl__TexCoord4s (short s, short t, short r, short q);
//    static void gl__TexCoord4sv (const short * v);
    static void gl__TexCoordPointer (int size, unsigned int type, int stride, const void * pointer);
    static void gl__TexEnvf (unsigned int target, unsigned int pname, float param);
//    static void gl__TexEnvfv (unsigned int target, unsigned int pname, const float * params);
//    static void gl__TexEnvi (unsigned int target, unsigned int pname, int param);
//    static void gl__TexEnviv (unsigned int target, unsigned int pname, const int * params);
    static void gl__TexGen__d (unsigned int coord, unsigned int pname, double param);
//    static void gl__TexGendv (unsigned int coord, unsigned int pname, const double * params);
//    static void gl__TexGenf (unsigned int coord, unsigned int pname, float param);
//    static void gl__TexGenfv (unsigned int coord, unsigned int pname, const float * params);
//    static void gl__TexGeni (unsigned int coord, unsigned int pname, int param);
//    static void gl__TexGeniv (unsigned int coord, unsigned int pname, const int * params);
    static void gl__TexImage1D (unsigned int target, int level, int internalformat, int width, int border, unsigned int format, unsigned int type, const void * pixels);
    static void gl__TexImage2D (unsigned int target, int level, int internalformat, int width, int height, int border, unsigned int format, unsigned int type, const void * pixels);
    static void gl__TexParameter__f (unsigned int target, unsigned int pname, float param);
//    static void gl__TexParameterfv (unsigned int target, unsigned int pname, const float * params);
//    static void gl__TexParameteri (unsigned int target, unsigned int pname, int param);
//    static void gl__TexParameteriv (unsigned int target, unsigned int pname, const int * params);
    static void gl__TexSubImage1D (unsigned int target, int level, int xoffset, int width, unsigned int format, unsigned int type, const void * pixels);
    static void gl__TexSubImage2D (unsigned int target, int level, int xoffset, int yoffset, int width, int height, unsigned int format, unsigned int type, const void * pixels);
    static void gl__Translate__d (double x, double y, double z);
//    static void gl__Translatef (float x, float y, float z);
    static void gl__Vertex__2d (double x, double y);
//    static void gl__Vertex2dv (const double * v);
//    static void gl__Vertex2f (float x, float y);
//    static void gl__Vertex2fv (const float * v);
//    static void gl__Vertex2i (int x, int y);
//    static void gl__Vertex2iv (const int * v);
//    static void gl__Vertex2s (short x, short y);
//    static void gl__Vertex2sv (const short * v);
    static void gl__Vertex__3d (double x, double y, double z);
//    static void gl__Vertex3dv (const double * v);
//    static void gl__Vertex3f (float x, float y, float z);
//    static void gl__Vertex3fv (const float * v);
//    static void gl__Vertex3i (int x, int y, int z);
//    static void gl__Vertex3iv (const int * v);
//    static void gl__Vertex3s (short x, short y, short z);
//    static void gl__Vertex3sv (const short * v);
    static void gl__Vertex__4d (double x, double y, double z, double w);
//    static void gl__Vertex4dv (const double * v);
//    static void gl__Vertex4f (float x, float y, float z, float w);
//    static void gl__Vertex4fv (const float * v);
//    static void gl__Vertex4i (int x, int y, int z, int w);
//    static void gl__Vertex4iv (const int * v);
//    static void gl__Vertex4s (short x, short y, short z, short w);
//    static void gl__Vertex4sv (const short * v);
    static void gl__VertexPointer (int size, unsigned int type, int stride, const void * pointer);
    static void gl__Viewport (int x, int y, int width, int height);
};

END_JUCE_NAMESPACE
#endif
