#include "jpils/jpils-commander.h"

const char *PILS::PilsCommander::bootExpression =
	"[pils-configuration:executable-filename] <-#-* \"/\" repeat"
	"{ +$ fn"
	"| :ok"
	"  list := fn . \"pils/english/system/system.\" ([pils-configuration:pils-filetype] -#$* \"np\");"
	"  fn <-# 1 <-#-* \"/\""
	"}"
	".:list find"
	"{ filename"
	"| :where"
	"  :if file (filename bug {}) text => text; :ok"
	"  text -#=* \"><:[module:. pils system boot\""
	"  -#=* \"><;\" +#^* \"><:\" *=* [\"><.\", \"><\"]"
	"  .({} **=** {\"pils-filetype\" := $ ok|:ok . -#$* \"np\"} {\"application-type\" := ?|:ok \"applet\"} read:)"
	"  --- where"
	"  boot: .filename .text"
	"}"
;
