/* This file is public domain

DO NOT EDIT.
This file was auto-generated by caseconverter.pils from specs in
http://unicode.org/Public/UNIDATA/UnicodeData.txt

Supports upper, lower and title casing but only where conversion does not
change the UTF8 byte count, i.e. the turkish i-variants are not converted at all.

*/

#include "pilsstring.h"
namespace PILS {
	const PilsString *PropertyCasingUpper::transform(const PILS_CHAR *source, size_t count, const std::locale &locale) const {
		PILS_CHAR fastBuffer[0x100];
		PILS_CHAR *buffer =
			count > 0x100 ? new PILS_CHAR[count] : fastBuffer;
		for (size_t i = 0; i < count; i++) {
			unsigned char c = source[i];
			switch (c) {
			case 0x61:
			case 0x62:
			case 0x63:
			case 0x64:
			case 0x65:
			case 0x66:
			case 0x67:
			case 0x68:
			case 0x69:
			case 0x6A:
			case 0x6B:
			case 0x6C:
			case 0x6D:
			case 0x6E:
			case 0x6F:
			case 0x70:
			case 0x71:
			case 0x72:
			case 0x73:
			case 0x74:
			case 0x75:
			case 0x76:
			case 0x77:
			case 0x78:
			case 0x79:
			case 0x7A:
				c -= 0x20;
				break;
			case 0xC2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x19;
					break;
				}
				break;
			case 0xC3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xA0:
				case 0xA1:
				case 0xA2:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
				case 0xAC:
				case 0xAD:
				case 0xAE:
				case 0xAF:
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
					c -= 0x20;
					break;
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xC5;
					c -= 0x07;
					break;
				}
				break;
			case 0xC4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c -= 0x01;
					break;
				}
				break;
			case 0xC5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
					buffer[i - 1] = (PILS_CHAR)0xC4;
					c += 0x3F;
					break;
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c -= 0x01;
					break;
				}
				break;
			case 0xC6:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x03;
					break;
				case 0x83:
				case 0x85:
				case 0x88:
				case 0x8C:
				case 0x92:
				case 0x99:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA8:
				case 0xAD:
				case 0xB0:
				case 0xB4:
				case 0xB6:
				case 0xB9:
				case 0xBD:
					c -= 0x01;
					break;
				case 0x95:
					buffer[i - 1] = (PILS_CHAR)0xC7;
					c += 0x21;
					break;
				case 0x9A:
					buffer[i - 1] = (PILS_CHAR)0xC8;
					c += 0x23;
					break;
				case 0x9E:
					buffer[i - 1] = (PILS_CHAR)0xC8;
					c += 0x02;
					break;
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xC7;
					c -= 0x08;
					break;
				}
				break;
			case 0xC7:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x85:
				case 0x88:
				case 0x8B:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB2:
				case 0xB5:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				case 0x86:
				case 0x89:
				case 0x8C:
				case 0xB3:
					c -= 0x02;
					break;
				case 0x9D:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0F;
					break;
				}
				break;
			case 0xC8:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xBC:
					c -= 0x01;
					break;
				}
				break;
			case 0xC9:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x82:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
					c -= 0x01;
					break;
				case 0x93:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x12;
					break;
				case 0x94:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0E;
					break;
				case 0x96:
				case 0x97:
				case 0xA0:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0D;
					break;
				case 0x99:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0A;
					break;
				case 0x9B:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0B;
					break;
				case 0xA3:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0F;
					break;
				case 0xA8:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x11;
					break;
				case 0xA9:
				case 0xAF:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x13;
					break;
				case 0xB2:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x15;
					break;
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x16;
					break;
				}
				break;
			case 0xCA:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x83:
				case 0x88:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x26;
					break;
				case 0x89:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c -= 0x05;
					break;
				case 0x8A:
				case 0x8B:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x27;
					break;
				case 0x8C:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c -= 0x07;
					break;
				case 0x92:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x25;
					break;
				}
				break;
			case 0xCD:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x85:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x14;
					break;
				case 0xB1:
				case 0xB3:
				case 0xB7:
					c -= 0x01;
					break;
				case 0xBB:
				case 0xBC:
				case 0xBD:
					buffer[i - 1] = (PILS_CHAR)0xCF;
					c += 0x02;
					break;
				}
				break;
			case 0xCE:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xAC:
					c -= 0x26;
					break;
				case 0xAD:
				case 0xAE:
				case 0xAF:
					c -= 0x25;
					break;
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x20;
					break;
				}
				break;
			case 0xCF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x20;
					break;
				case 0x82:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x21;
					break;
				case 0x8C:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x00;
					break;
				case 0x8D:
				case 0x8E:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x01;
					break;
				case 0x90:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x02;
					break;
				case 0x91:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x07;
					break;
				case 0x95:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x11;
					break;
				case 0x96:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x0A;
					break;
				case 0x97:
					c -= 0x08;
					break;
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB8:
				case 0xBB:
					c -= 0x01;
					break;
				case 0xB0:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x16;
					break;
				case 0xB1:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x10;
					break;
				case 0xB2:
					c += 0x07;
					break;
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x20;
					break;
				}
				break;
			case 0xD0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x20;
					break;
				}
				break;
			case 0xD1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
				case 0x8C:
				case 0x8D:
				case 0x8E:
				case 0x8F:
					buffer[i - 1] = (PILS_CHAR)0xD0;
					c += 0x20;
					break;
				case 0x90:
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
				case 0x97:
				case 0x98:
				case 0x99:
				case 0x9A:
				case 0x9B:
				case 0x9C:
				case 0x9D:
				case 0x9E:
				case 0x9F:
					buffer[i - 1] = (PILS_CHAR)0xD0;
					c -= 0x10;
					break;
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				}
				break;
			case 0xD2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				}
				break;
			case 0xD3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				case 0x8F:
					c -= 0x0F;
					break;
				}
				break;
			case 0xD4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
					c -= 0x01;
					break;
				}
				break;
			case 0xD5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xA1:
				case 0xA2:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
				case 0xAC:
				case 0xAD:
				case 0xAE:
				case 0xAF:
					buffer[i - 1] = (PILS_CHAR)0xD4;
					c += 0x10;
					break;
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x30;
					break;
				}
				break;
			case 0xD6:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
					buffer[i - 1] = (PILS_CHAR)0xD5;
					c += 0x10;
					break;
				}
				break;
			case 0xE1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB5:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB9:
						buffer[i - 2] = (PILS_CHAR)0xEA;
						buffer[i - 1] = (PILS_CHAR)0x9D;
						c += 0x04;
						break;
					case 0xBD:
						buffer[i - 2] = (PILS_CHAR)0xE2;
						buffer[i - 1] = (PILS_CHAR)0xB1;
						c -= 0x1A;
						break;
					}
					break;
				case 0xB8:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xB9:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xBA:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					case 0x9B:
						buffer[i - 1] = (PILS_CHAR)0xB9;
						c += 0x05;
						break;
					}
					break;
				case 0xBB:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xBC:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
						c += 0x08;
						break;
					}
					break;
				case 0xBD:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
						c += 0x08;
						break;
					case 0xB0:
					case 0xB1:
						buffer[i - 1] = (PILS_CHAR)0xBE;
						c += 0x0A;
						break;
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x2A;
						break;
					case 0xB6:
					case 0xB7:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x1C;
						break;
					case 0xB8:
					case 0xB9:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x00;
						break;
					case 0xBA:
					case 0xBB:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x10;
						break;
					case 0xBC:
					case 0xBD:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x02;
						break;
					}
					break;
				case 0xBE:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xB0:
					case 0xB1:
						c += 0x08;
						break;
					case 0xB3:
						c += 0x09;
						break;
					}
					break;
				case 0xBF:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x83:
					case 0xB3:
						c += 0x09;
						break;
					case 0x90:
					case 0x91:
					case 0xA0:
					case 0xA1:
						c += 0x08;
						break;
					case 0xA5:
						c += 0x07;
						break;
					}
					break;
				}
				break;
			case 0xE2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x85:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x8E:
						buffer[i - 1] = (PILS_CHAR)0x84;
						c += 0x24;
						break;
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						c -= 0x10;
						break;
					}
					break;
				case 0x86:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x84:
						c -= 0x01;
						break;
					}
					break;
				case 0x93:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
						buffer[i - 1] = (PILS_CHAR)0x92;
						c += 0x26;
						break;
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
						c -= 0x1A;
						break;
					}
					break;
				case 0xB0:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						c -= 0x30;
						break;
					}
					break;
				case 0xB1:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
						buffer[i - 1] = (PILS_CHAR)0xB0;
						c += 0x10;
						break;
					case 0xA1:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xB3:
					case 0xB6:
						c -= 0x01;
						break;
					}
					break;
				case 0xB2:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xB3:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
						c -= 0x01;
						break;
					}
					break;
				case 0xB4:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0x82;
						c += 0x20;
						break;
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0x83;
						c -= 0x20;
						break;
					}
					break;
				}
				break;
			case 0xEA:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x99:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
						c -= 0x01;
						break;
					}
					break;
				case 0x9A:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
						c -= 0x01;
						break;
					}
					break;
				case 0x9C:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0x9D:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xBA:
					case 0xBC:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0x9E:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x8C:
						c -= 0x01;
						break;
					}
					break;
				}
				break;
			case 0xEF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xBD:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
						buffer[i - 1] = (PILS_CHAR)0xBC;
						c += 0x20;
						break;
					}
					break;
				}
				break;
			case 0xF0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x90:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x90:
						buffer[i++] = c;
						if (i == count) goto done;
						c = source[i];
						switch (c) {
						case 0xA8:
						case 0xA9:
						case 0xAA:
						case 0xAB:
						case 0xAC:
						case 0xAD:
						case 0xAE:
						case 0xAF:
						case 0xB0:
						case 0xB1:
						case 0xB2:
						case 0xB3:
						case 0xB4:
						case 0xB5:
						case 0xB6:
						case 0xB7:
						case 0xB8:
						case 0xB9:
						case 0xBA:
						case 0xBB:
						case 0xBC:
						case 0xBD:
						case 0xBE:
						case 0xBF:
							c -= 0x28;
							break;
						}
						break;
					case 0x91:
						buffer[i++] = c;
						if (i == count) goto done;
						c = source[i];
						switch (c) {
						case 0x80:
						case 0x81:
						case 0x82:
						case 0x83:
						case 0x84:
						case 0x85:
						case 0x86:
						case 0x87:
						case 0x88:
						case 0x89:
						case 0x8A:
						case 0x8B:
						case 0x8C:
						case 0x8D:
						case 0x8E:
						case 0x8F:
							buffer[i - 1] = (PILS_CHAR)0x90;
							c += 0x18;
							break;
						}
						break;
					}
					break;
				}
				break;
			}
			buffer[i] = c;
		}
	done:
		const PilsString *string = PilsString::get(buffer, count);
		if (count > 0x100) delete buffer;
		return string;
	}

	const PilsString *PropertyCasingLower::transform(const PILS_CHAR *source, size_t count, const std::locale &locale) const {
		PILS_CHAR fastBuffer[0x100];
		PILS_CHAR *buffer =
			count > 0x100 ? new PILS_CHAR[count] : fastBuffer;
		for (size_t i = 0; i < count; i++) {
			unsigned char c = source[i];
			switch (c) {
			case 0x41:
			case 0x42:
			case 0x43:
			case 0x44:
			case 0x45:
			case 0x46:
			case 0x47:
			case 0x48:
			case 0x49:
			case 0x4A:
			case 0x4B:
			case 0x4C:
			case 0x4D:
			case 0x4E:
			case 0x4F:
			case 0x50:
			case 0x51:
			case 0x52:
			case 0x53:
			case 0x54:
			case 0x55:
			case 0x56:
			case 0x57:
			case 0x58:
			case 0x59:
			case 0x5A:
				c += 0x20;
				break;
			case 0xC3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
				case 0x8C:
				case 0x8D:
				case 0x8E:
				case 0x8F:
				case 0x90:
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
				case 0x98:
				case 0x99:
				case 0x9A:
				case 0x9B:
				case 0x9C:
				case 0x9D:
				case 0x9E:
					c += 0x20;
					break;
				}
				break;
			case 0xC4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB2:
				case 0xB4:
				case 0xB6:
				case 0xB9:
				case 0xBB:
				case 0xBD:
					c += 0x01;
					break;
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xC5;
					c -= 0x3F;
					break;
				}
				break;
			case 0xC5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB0:
				case 0xB2:
				case 0xB4:
				case 0xB6:
				case 0xB9:
				case 0xBB:
				case 0xBD:
					c += 0x01;
					break;
				case 0xB8:
					buffer[i - 1] = (PILS_CHAR)0xC3;
					c += 0x07;
					break;
				}
				break;
			case 0xC6:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x12;
					break;
				case 0x82:
				case 0x84:
				case 0x87:
				case 0x8B:
				case 0x91:
				case 0x98:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA7:
				case 0xAC:
				case 0xAF:
				case 0xB3:
				case 0xB5:
				case 0xB8:
				case 0xBC:
					c += 0x01;
					break;
				case 0x86:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x0E;
					break;
				case 0x89:
				case 0x8A:
				case 0x93:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x0D;
					break;
				case 0x8E:
					buffer[i - 1] = (PILS_CHAR)0xC7;
					c += 0x0F;
					break;
				case 0x8F:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x0A;
					break;
				case 0x90:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x0B;
					break;
				case 0x94:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x0F;
					break;
				case 0x96:
				case 0x9C:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x13;
					break;
				case 0x97:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x11;
					break;
				case 0x9D:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x15;
					break;
				case 0x9F:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x16;
					break;
				case 0xA6:
				case 0xA9:
				case 0xAE:
					buffer[i - 1] = (PILS_CHAR)0xCA;
					c -= 0x26;
					break;
				case 0xB1:
				case 0xB2:
					buffer[i - 1] = (PILS_CHAR)0xCA;
					c -= 0x27;
					break;
				case 0xB7:
					buffer[i - 1] = (PILS_CHAR)0xCA;
					c -= 0x25;
					break;
				}
				break;
			case 0xC7:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x84:
				case 0x87:
				case 0x8A:
				case 0xB1:
					c += 0x02;
					break;
				case 0x85:
				case 0x88:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB2:
				case 0xB4:
				case 0xB8:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c += 0x01;
					break;
				case 0xB6:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x21;
					break;
				case 0xB7:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x08;
					break;
				}
				break;
			case 0xC8:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB0:
				case 0xB2:
				case 0xBB:
					c += 0x01;
					break;
				case 0xA0:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x02;
					break;
				case 0xBD:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x23;
					break;
				}
				break;
			case 0xC9:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
					c += 0x01;
					break;
				case 0x83:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x03;
					break;
				case 0x84:
					buffer[i - 1] = (PILS_CHAR)0xCA;
					c += 0x05;
					break;
				case 0x85:
					buffer[i - 1] = (PILS_CHAR)0xCA;
					c += 0x07;
					break;
				}
				break;
			case 0xCD:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB0:
				case 0xB2:
				case 0xB6:
					c += 0x01;
					break;
				}
				break;
			case 0xCE:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x86:
					c += 0x26;
					break;
				case 0x88:
				case 0x89:
				case 0x8A:
					c += 0x25;
					break;
				case 0x8C:
					buffer[i - 1] = (PILS_CHAR)0xCF;
					c -= 0x00;
					break;
				case 0x8E:
				case 0x8F:
					buffer[i - 1] = (PILS_CHAR)0xCF;
					c -= 0x01;
					break;
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
				case 0x97:
				case 0x98:
				case 0x99:
				case 0x9A:
				case 0x9B:
				case 0x9C:
				case 0x9D:
				case 0x9E:
				case 0x9F:
					c += 0x20;
					break;
				case 0xA0:
				case 0xA1:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
					buffer[i - 1] = (PILS_CHAR)0xCF;
					c -= 0x20;
					break;
				}
				break;
			case 0xCF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x8F:
					c += 0x08;
					break;
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB7:
				case 0xBA:
					c += 0x01;
					break;
				case 0xB4:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x04;
					break;
				case 0xB9:
					c -= 0x07;
					break;
				case 0xBD:
				case 0xBE:
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xCD;
					c -= 0x02;
					break;
				}
				break;
			case 0xD0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
				case 0x8C:
				case 0x8D:
				case 0x8E:
				case 0x8F:
					buffer[i - 1] = (PILS_CHAR)0xD1;
					c += 0x10;
					break;
				case 0x90:
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
				case 0x97:
				case 0x98:
				case 0x99:
				case 0x9A:
				case 0x9B:
				case 0x9C:
				case 0x9D:
				case 0x9E:
				case 0x9F:
					c += 0x20;
					break;
				case 0xA0:
				case 0xA1:
				case 0xA2:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
				case 0xAC:
				case 0xAD:
				case 0xAE:
				case 0xAF:
					buffer[i - 1] = (PILS_CHAR)0xD1;
					c -= 0x20;
					break;
				}
				break;
			case 0xD1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB0:
				case 0xB2:
				case 0xB4:
				case 0xB6:
				case 0xB8:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c += 0x01;
					break;
				}
				break;
			case 0xD2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB0:
				case 0xB2:
				case 0xB4:
				case 0xB6:
				case 0xB8:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c += 0x01;
					break;
				}
				break;
			case 0xD3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
					c += 0x0F;
					break;
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
				case 0xA4:
				case 0xA6:
				case 0xA8:
				case 0xAA:
				case 0xAC:
				case 0xAE:
				case 0xB0:
				case 0xB2:
				case 0xB4:
				case 0xB6:
				case 0xB8:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c += 0x01;
					break;
				}
				break;
			case 0xD4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9E:
				case 0xA0:
				case 0xA2:
					c += 0x01;
					break;
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xD5;
					c -= 0x10;
					break;
				}
				break;
			case 0xD5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
				case 0x8C:
				case 0x8D:
				case 0x8E:
				case 0x8F:
					c += 0x30;
					break;
				case 0x90:
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
					buffer[i - 1] = (PILS_CHAR)0xD6;
					c -= 0x10;
					break;
				}
				break;
			case 0xE1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x82:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						buffer[i - 2] = (PILS_CHAR)0xE2;
						buffer[i - 1] = (PILS_CHAR)0xB4;
						c -= 0x20;
						break;
					}
					break;
				case 0x83:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
						buffer[i - 2] = (PILS_CHAR)0xE2;
						buffer[i - 1] = (PILS_CHAR)0xB4;
						c += 0x20;
						break;
					}
					break;
				case 0xB8:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB0:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0xB9:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB0:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0xBA:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB0:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0xBB:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB0:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0xBC:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						c -= 0x08;
						break;
					}
					break;
				case 0xBD:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
						c -= 0x08;
						break;
					}
					break;
				case 0xBE:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
					case 0xB8:
					case 0xB9:
						c -= 0x08;
						break;
					case 0xBA:
					case 0xBB:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c -= 0x0A;
						break;
					case 0xBC:
						c -= 0x09;
						break;
					}
					break;
				case 0xBF:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c += 0x2A;
						break;
					case 0x8C:
					case 0xBC:
						c -= 0x09;
						break;
					case 0x98:
					case 0x99:
					case 0xA8:
					case 0xA9:
						c -= 0x08;
						break;
					case 0x9A:
					case 0x9B:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c += 0x1C;
						break;
					case 0xAA:
					case 0xAB:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c += 0x10;
						break;
					case 0xAC:
						c -= 0x07;
						break;
					case 0xB8:
					case 0xB9:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c -= 0x00;
						break;
					case 0xBA:
					case 0xBB:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c += 0x02;
						break;
					}
					break;
				}
				break;
			case 0xE2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x84:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB2:
						buffer[i - 1] = (PILS_CHAR)0x85;
						c -= 0x24;
						break;
					}
					break;
				case 0x85:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
						c += 0x10;
						break;
					}
					break;
				case 0x86:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x83:
						c += 0x01;
						break;
					}
					break;
				case 0x92:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						buffer[i - 1] = (PILS_CHAR)0x93;
						c -= 0x26;
						break;
					}
					break;
				case 0x93:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
						c += 0x1A;
						break;
					}
					break;
				case 0xB0:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
						c += 0x30;
						break;
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
						buffer[i - 1] = (PILS_CHAR)0xB1;
						c -= 0x10;
						break;
					}
					break;
				case 0xB1:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA0:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xB2:
					case 0xB5:
						c += 0x01;
						break;
					case 0xA3:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0xB5;
						c += 0x1A;
						break;
					}
					break;
				case 0xB2:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB0:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0xB3:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
						c += 0x01;
						break;
					}
					break;
				}
				break;
			case 0xEA:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x99:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
						c += 0x01;
						break;
					}
					break;
				case 0x9A:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
						c += 0x01;
						break;
					}
					break;
				case 0x9C:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB2:
					case 0xB4:
					case 0xB6:
					case 0xB8:
					case 0xBA:
					case 0xBC:
					case 0xBE:
						c += 0x01;
						break;
					}
					break;
				case 0x9D:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x88:
					case 0x8A:
					case 0x8C:
					case 0x8E:
					case 0x90:
					case 0x92:
					case 0x94:
					case 0x96:
					case 0x98:
					case 0x9A:
					case 0x9C:
					case 0x9E:
					case 0xA0:
					case 0xA2:
					case 0xA4:
					case 0xA6:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xAE:
					case 0xB9:
					case 0xBB:
					case 0xBE:
						c += 0x01;
						break;
					case 0xBD:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0xB5;
						c -= 0x04;
						break;
					}
					break;
				case 0x9E:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x82:
					case 0x84:
					case 0x86:
					case 0x8B:
						c += 0x01;
						break;
					}
					break;
				}
				break;
			case 0xEF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xBC:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
					case 0xAA:
					case 0xAB:
					case 0xAC:
					case 0xAD:
					case 0xAE:
					case 0xAF:
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
						buffer[i - 1] = (PILS_CHAR)0xBD;
						c -= 0x20;
						break;
					}
					break;
				}
				break;
			case 0xF0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x90:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x90:
						buffer[i++] = c;
						if (i == count) goto done;
						c = source[i];
						switch (c) {
						case 0x80:
						case 0x81:
						case 0x82:
						case 0x83:
						case 0x84:
						case 0x85:
						case 0x86:
						case 0x87:
						case 0x88:
						case 0x89:
						case 0x8A:
						case 0x8B:
						case 0x8C:
						case 0x8D:
						case 0x8E:
						case 0x8F:
						case 0x90:
						case 0x91:
						case 0x92:
						case 0x93:
						case 0x94:
						case 0x95:
						case 0x96:
						case 0x97:
							c += 0x28;
							break;
						case 0x98:
						case 0x99:
						case 0x9A:
						case 0x9B:
						case 0x9C:
						case 0x9D:
						case 0x9E:
						case 0x9F:
						case 0xA0:
						case 0xA1:
						case 0xA2:
						case 0xA3:
						case 0xA4:
						case 0xA5:
						case 0xA6:
						case 0xA7:
							buffer[i - 1] = (PILS_CHAR)0x91;
							c -= 0x18;
							break;
						}
						break;
					}
					break;
				}
				break;
			}
			buffer[i] = c;
		}
	done:
		const PilsString *string = PilsString::get(buffer, count);
		if (count > 0x100) delete buffer;
		return string;
	}

	const PilsString *PropertyCasingTitle::transform(const PILS_CHAR *source, size_t count, const std::locale &locale) const {
		PILS_CHAR fastBuffer[0x100];
		PILS_CHAR *buffer =
			count > 0x100 ? new PILS_CHAR[count] : fastBuffer;
		for (size_t i = 0; i < count; i++) {
			unsigned char c = source[i];
			if (!i) //Only first char gets converted
			switch (c) {
			case 0x61:
			case 0x62:
			case 0x63:
			case 0x64:
			case 0x65:
			case 0x66:
			case 0x67:
			case 0x68:
			case 0x69:
			case 0x6A:
			case 0x6B:
			case 0x6C:
			case 0x6D:
			case 0x6E:
			case 0x6F:
			case 0x70:
			case 0x71:
			case 0x72:
			case 0x73:
			case 0x74:
			case 0x75:
			case 0x76:
			case 0x77:
			case 0x78:
			case 0x79:
			case 0x7A:
				c -= 0x20;
				break;
			case 0xC2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x19;
					break;
				}
				break;
			case 0xC3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xA0:
				case 0xA1:
				case 0xA2:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
				case 0xAC:
				case 0xAD:
				case 0xAE:
				case 0xAF:
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
					c -= 0x20;
					break;
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xC5;
					c -= 0x07;
					break;
				}
				break;
			case 0xC4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c -= 0x01;
					break;
				}
				break;
			case 0xC5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
					buffer[i - 1] = (PILS_CHAR)0xC4;
					c += 0x3F;
					break;
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xBA:
				case 0xBC:
				case 0xBE:
					c -= 0x01;
					break;
				}
				break;
			case 0xC6:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c += 0x03;
					break;
				case 0x83:
				case 0x85:
				case 0x88:
				case 0x8C:
				case 0x92:
				case 0x99:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA8:
				case 0xAD:
				case 0xB0:
				case 0xB4:
				case 0xB6:
				case 0xB9:
				case 0xBD:
					c -= 0x01;
					break;
				case 0x95:
					buffer[i - 1] = (PILS_CHAR)0xC7;
					c += 0x21;
					break;
				case 0x9A:
					buffer[i - 1] = (PILS_CHAR)0xC8;
					c += 0x23;
					break;
				case 0x9E:
					buffer[i - 1] = (PILS_CHAR)0xC8;
					c += 0x02;
					break;
				case 0xBF:
					buffer[i - 1] = (PILS_CHAR)0xC7;
					c -= 0x08;
					break;
				}
				break;
			case 0xC7:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x84:
				case 0x87:
				case 0x8A:
				case 0xB1:
					c += 0x01;
					break;
				case 0x85:
				case 0x88:
				case 0x8B:
				case 0xB2:
					c -= 0x00;
					break;
				case 0x86:
				case 0x89:
				case 0x8C:
				case 0x8E:
				case 0x90:
				case 0x92:
				case 0x94:
				case 0x96:
				case 0x98:
				case 0x9A:
				case 0x9C:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB3:
				case 0xB5:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				case 0x9D:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0F;
					break;
				}
				break;
			case 0xC8:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xBC:
					c -= 0x01;
					break;
				}
				break;
			case 0xC9:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x82:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
					c -= 0x01;
					break;
				case 0x93:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x12;
					break;
				case 0x94:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0E;
					break;
				case 0x96:
				case 0x97:
				case 0xA0:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0D;
					break;
				case 0x99:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0A;
					break;
				case 0x9B:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0B;
					break;
				case 0xA3:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x0F;
					break;
				case 0xA8:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x11;
					break;
				case 0xA9:
				case 0xAF:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x13;
					break;
				case 0xB2:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x15;
					break;
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c -= 0x16;
					break;
				}
				break;
			case 0xCA:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x83:
				case 0x88:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x26;
					break;
				case 0x89:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c -= 0x05;
					break;
				case 0x8A:
				case 0x8B:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x27;
					break;
				case 0x8C:
					buffer[i - 1] = (PILS_CHAR)0xC9;
					c -= 0x07;
					break;
				case 0x92:
					buffer[i - 1] = (PILS_CHAR)0xC6;
					c += 0x25;
					break;
				}
				break;
			case 0xCD:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x85:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x14;
					break;
				case 0xB1:
				case 0xB3:
				case 0xB7:
					c -= 0x01;
					break;
				case 0xBB:
				case 0xBC:
				case 0xBD:
					buffer[i - 1] = (PILS_CHAR)0xCF;
					c += 0x02;
					break;
				}
				break;
			case 0xCE:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xAC:
					c -= 0x26;
					break;
				case 0xAD:
				case 0xAE:
				case 0xAF:
					c -= 0x25;
					break;
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x20;
					break;
				}
				break;
			case 0xCF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x20;
					break;
				case 0x82:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x21;
					break;
				case 0x8C:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x00;
					break;
				case 0x8D:
				case 0x8E:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x01;
					break;
				case 0x90:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x02;
					break;
				case 0x91:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x07;
					break;
				case 0x95:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x11;
					break;
				case 0x96:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c += 0x0A;
					break;
				case 0x97:
					c -= 0x08;
					break;
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB8:
				case 0xBB:
					c -= 0x01;
					break;
				case 0xB0:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x16;
					break;
				case 0xB1:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x10;
					break;
				case 0xB2:
					c += 0x07;
					break;
				case 0xB5:
					buffer[i - 1] = (PILS_CHAR)0xCE;
					c -= 0x20;
					break;
				}
				break;
			case 0xD0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x20;
					break;
				}
				break;
			case 0xD1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
				case 0x87:
				case 0x88:
				case 0x89:
				case 0x8A:
				case 0x8B:
				case 0x8C:
				case 0x8D:
				case 0x8E:
				case 0x8F:
					buffer[i - 1] = (PILS_CHAR)0xD0;
					c += 0x20;
					break;
				case 0x90:
				case 0x91:
				case 0x92:
				case 0x93:
				case 0x94:
				case 0x95:
				case 0x96:
				case 0x97:
				case 0x98:
				case 0x99:
				case 0x9A:
				case 0x9B:
				case 0x9C:
				case 0x9D:
				case 0x9E:
				case 0x9F:
					buffer[i - 1] = (PILS_CHAR)0xD0;
					c -= 0x10;
					break;
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				}
				break;
			case 0xD2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				}
				break;
			case 0xD3:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x82:
				case 0x84:
				case 0x86:
				case 0x88:
				case 0x8A:
				case 0x8C:
				case 0x8E:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
				case 0xA5:
				case 0xA7:
				case 0xA9:
				case 0xAB:
				case 0xAD:
				case 0xAF:
				case 0xB1:
				case 0xB3:
				case 0xB5:
				case 0xB7:
				case 0xB9:
				case 0xBB:
				case 0xBD:
				case 0xBF:
					c -= 0x01;
					break;
				case 0x8F:
					c -= 0x0F;
					break;
				}
				break;
			case 0xD4:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x81:
				case 0x83:
				case 0x85:
				case 0x87:
				case 0x89:
				case 0x8B:
				case 0x8D:
				case 0x8F:
				case 0x91:
				case 0x93:
				case 0x95:
				case 0x97:
				case 0x99:
				case 0x9B:
				case 0x9D:
				case 0x9F:
				case 0xA1:
				case 0xA3:
					c -= 0x01;
					break;
				}
				break;
			case 0xD5:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xA1:
				case 0xA2:
				case 0xA3:
				case 0xA4:
				case 0xA5:
				case 0xA6:
				case 0xA7:
				case 0xA8:
				case 0xA9:
				case 0xAA:
				case 0xAB:
				case 0xAC:
				case 0xAD:
				case 0xAE:
				case 0xAF:
					buffer[i - 1] = (PILS_CHAR)0xD4;
					c += 0x10;
					break;
				case 0xB0:
				case 0xB1:
				case 0xB2:
				case 0xB3:
				case 0xB4:
				case 0xB5:
				case 0xB6:
				case 0xB7:
				case 0xB8:
				case 0xB9:
				case 0xBA:
				case 0xBB:
				case 0xBC:
				case 0xBD:
				case 0xBE:
				case 0xBF:
					c -= 0x30;
					break;
				}
				break;
			case 0xD6:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x80:
				case 0x81:
				case 0x82:
				case 0x83:
				case 0x84:
				case 0x85:
				case 0x86:
					buffer[i - 1] = (PILS_CHAR)0xD5;
					c += 0x10;
					break;
				}
				break;
			case 0xE1:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xB5:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB9:
						buffer[i - 2] = (PILS_CHAR)0xEA;
						buffer[i - 1] = (PILS_CHAR)0x9D;
						c += 0x04;
						break;
					case 0xBD:
						buffer[i - 2] = (PILS_CHAR)0xE2;
						buffer[i - 1] = (PILS_CHAR)0xB1;
						c -= 0x1A;
						break;
					}
					break;
				case 0xB8:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xB9:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xBA:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					case 0x9B:
						buffer[i - 1] = (PILS_CHAR)0xB9;
						c += 0x05;
						break;
					}
					break;
				case 0xBB:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xBC:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
						c += 0x08;
						break;
					}
					break;
				case 0xBD:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
						c += 0x08;
						break;
					case 0xB0:
					case 0xB1:
						buffer[i - 1] = (PILS_CHAR)0xBE;
						c += 0x0A;
						break;
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x2A;
						break;
					case 0xB6:
					case 0xB7:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x1C;
						break;
					case 0xB8:
					case 0xB9:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x00;
						break;
					case 0xBA:
					case 0xBB:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x10;
						break;
					case 0xBC:
					case 0xBD:
						buffer[i - 1] = (PILS_CHAR)0xBF;
						c -= 0x02;
						break;
					}
					break;
				case 0xBE:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xB0:
					case 0xB1:
						c += 0x08;
						break;
					case 0xB3:
						c += 0x09;
						break;
					}
					break;
				case 0xBF:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x83:
					case 0xB3:
						c += 0x09;
						break;
					case 0x90:
					case 0x91:
					case 0xA0:
					case 0xA1:
						c += 0x08;
						break;
					case 0xA5:
						c += 0x07;
						break;
					}
					break;
				}
				break;
			case 0xE2:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x85:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x8E:
						buffer[i - 1] = (PILS_CHAR)0x84;
						c += 0x24;
						break;
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						c -= 0x10;
						break;
					}
					break;
				case 0x86:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x84:
						c -= 0x01;
						break;
					}
					break;
				case 0x93:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
						buffer[i - 1] = (PILS_CHAR)0x92;
						c += 0x26;
						break;
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
					case 0xA6:
					case 0xA7:
					case 0xA8:
					case 0xA9:
						c -= 0x1A;
						break;
					}
					break;
				case 0xB0:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xB0:
					case 0xB1:
					case 0xB2:
					case 0xB3:
					case 0xB4:
					case 0xB5:
					case 0xB6:
					case 0xB7:
					case 0xB8:
					case 0xB9:
					case 0xBA:
					case 0xBB:
					case 0xBC:
					case 0xBD:
					case 0xBE:
					case 0xBF:
						c -= 0x30;
						break;
					}
					break;
				case 0xB1:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
						buffer[i - 1] = (PILS_CHAR)0xB0;
						c += 0x10;
						break;
					case 0xA1:
					case 0xA8:
					case 0xAA:
					case 0xAC:
					case 0xB3:
					case 0xB6:
						c -= 0x01;
						break;
					}
					break;
				case 0xB2:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB1:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0xB3:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
						c -= 0x01;
						break;
					}
					break;
				case 0xB4:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x80:
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
					case 0x9B:
					case 0x9C:
					case 0x9D:
					case 0x9E:
					case 0x9F:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0x82;
						c += 0x20;
						break;
					case 0xA0:
					case 0xA1:
					case 0xA2:
					case 0xA3:
					case 0xA4:
					case 0xA5:
						buffer[i - 2] = (PILS_CHAR)0xE1;
						buffer[i - 1] = (PILS_CHAR)0x83;
						c -= 0x20;
						break;
					}
					break;
				}
				break;
			case 0xEA:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x99:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
						c -= 0x01;
						break;
					}
					break;
				case 0x9A:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
						c -= 0x01;
						break;
					}
					break;
				case 0x9C:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xB3:
					case 0xB5:
					case 0xB7:
					case 0xB9:
					case 0xBB:
					case 0xBD:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0x9D:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x89:
					case 0x8B:
					case 0x8D:
					case 0x8F:
					case 0x91:
					case 0x93:
					case 0x95:
					case 0x97:
					case 0x99:
					case 0x9B:
					case 0x9D:
					case 0x9F:
					case 0xA1:
					case 0xA3:
					case 0xA5:
					case 0xA7:
					case 0xA9:
					case 0xAB:
					case 0xAD:
					case 0xAF:
					case 0xBA:
					case 0xBC:
					case 0xBF:
						c -= 0x01;
						break;
					}
					break;
				case 0x9E:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x83:
					case 0x85:
					case 0x87:
					case 0x8C:
						c -= 0x01;
						break;
					}
					break;
				}
				break;
			case 0xEF:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0xBD:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x81:
					case 0x82:
					case 0x83:
					case 0x84:
					case 0x85:
					case 0x86:
					case 0x87:
					case 0x88:
					case 0x89:
					case 0x8A:
					case 0x8B:
					case 0x8C:
					case 0x8D:
					case 0x8E:
					case 0x8F:
					case 0x90:
					case 0x91:
					case 0x92:
					case 0x93:
					case 0x94:
					case 0x95:
					case 0x96:
					case 0x97:
					case 0x98:
					case 0x99:
					case 0x9A:
						buffer[i - 1] = (PILS_CHAR)0xBC;
						c += 0x20;
						break;
					}
					break;
				}
				break;
			case 0xF0:
				buffer[i++] = c;
				if (i == count) goto done;
				c = source[i];
				switch (c) {
				case 0x90:
					buffer[i++] = c;
					if (i == count) goto done;
					c = source[i];
					switch (c) {
					case 0x90:
						buffer[i++] = c;
						if (i == count) goto done;
						c = source[i];
						switch (c) {
						case 0xA8:
						case 0xA9:
						case 0xAA:
						case 0xAB:
						case 0xAC:
						case 0xAD:
						case 0xAE:
						case 0xAF:
						case 0xB0:
						case 0xB1:
						case 0xB2:
						case 0xB3:
						case 0xB4:
						case 0xB5:
						case 0xB6:
						case 0xB7:
						case 0xB8:
						case 0xB9:
						case 0xBA:
						case 0xBB:
						case 0xBC:
						case 0xBD:
						case 0xBE:
						case 0xBF:
							c -= 0x28;
							break;
						}
						break;
					case 0x91:
						buffer[i++] = c;
						if (i == count) goto done;
						c = source[i];
						switch (c) {
						case 0x80:
						case 0x81:
						case 0x82:
						case 0x83:
						case 0x84:
						case 0x85:
						case 0x86:
						case 0x87:
						case 0x88:
						case 0x89:
						case 0x8A:
						case 0x8B:
						case 0x8C:
						case 0x8D:
						case 0x8E:
						case 0x8F:
							buffer[i - 1] = (PILS_CHAR)0x90;
							c += 0x18;
							break;
						}
						break;
					}
					break;
				}
				break;
			}
			buffer[i] = c;
		}
	done:
		const PilsString *string = PilsString::get(buffer, count);
		if (count > 0x100) delete buffer;
		return string;
	}
}
