/* This file is public domain

DO NOT EDIT.
This file was auto-generated by language-switch.pils from specs in
http://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt

Converts 2-3 character code to lower-case English language name.
Caller should substitute "english" when no translation is available.

Used selecting user language at boot.
*/

const char *language_code_to_english_language_name(char c0, char c1, char c2)
{
    if (c2 < 'a' && c2 > 'z') c2 = '\0';
    switch (c0)
    {
    case 'a':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "afar";
            }
            break;
        case 'b':
            switch (c2)
            {
            case '\0':
            case 'k':
                return "abkhazian";
            }
            break;
        case 'c':
            switch (c2)
            {
            case 'e':
                return "achinese";
            case 'h':
                return "acoli";
            }
            break;
        case 'd':
            switch (c2)
            {
            case 'a':
                return "adangme";
            case 'y':
                return "adyghe";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
                return "avestan";
            }
            break;
        case 'f':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "afrikaans";
            case 'a':
                return "afro-asiatic";
            case 'h':
                return "afrihili";
            }
            break;
        case 'i':
            switch (c2)
            {
            case 'n':
                return "ainu";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "akan";
            case 'k':
                return "akkadian";
            }
            break;
        case 'l':
            switch (c2)
            {
            case 'b':
                return "albanian";
            case 'e':
                return "aleut";
            case 'g':
                return "algonquian";
            case 't':
                return "southern-altai";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
            case 'h':
                return "amharic";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "aragonese";
            case 'g':
                return "old-english";
            case 'p':
                return "angika";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'a':
                return "apache";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "arabic";
            case 'c':
                return "official-aramaic";
            case 'g':
                return "aragonese";
            case 'm':
                return "armenian";
            case 'n':
                return "mapudungun";
            case 'p':
                return "arapaho";
            case 't':
                return "artificial";
            case 'w':
                return "arawak";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "assamese";
            case 't':
                return "asturian";
            }
            break;
        case 't':
            switch (c2)
            {
            case 'h':
                return "athapascan";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 's':
                return "australian";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "avaric";
            case 'e':
                return "avestan";
            }
            break;
        case 'w':
            switch (c2)
            {
            case 'a':
                return "awadhi";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "aymara";
            }
            break;
        case 'z':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "azerbaijani";
            }
            break;
        }
        break;
    case 'b':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'k':
                return "bashkir";
            case 'd':
                return "banda";
            case 'i':
                return "bamileke";
            case 'l':
                return "baluchi";
            case 'm':
                return "bambara";
            case 'n':
                return "balinese";
            case 'q':
                return "basque";
            case 's':
                return "basa";
            case 't':
                return "baltic";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "belarusian";
            case 'j':
                return "beja";
            case 'm':
                return "bemba";
            case 'n':
                return "bengali";
            case 'r':
                return "berber";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "bulgarian";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
                return "bihari";
            case 'o':
                return "bhojpuri";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 's':
                return "bislama";
            case 'h':
                return "bihari";
            case 'k':
                return "bikol";
            case 'n':
                return "bini";
            }
            break;
        case 'l':
            switch (c2)
            {
            case 'a':
                return "siksika";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
                return "bambara";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "bengali";
            case 't':
                return "bantu";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'd':
                return "tibetan";
            case 's':
                return "bosnian";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "breton";
            case 'a':
                return "braj";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
                return "bosnian";
            }
            break;
        case 't':
            switch (c2)
            {
            case 'k':
                return "batak";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'a':
                return "buriat";
            case 'g':
                return "buginese";
            case 'l':
                return "bulgarian";
            case 'r':
                return "burmese";
            }
            break;
        case 'y':
            switch (c2)
            {
            case 'n':
                return "blin";
            }
            break;
        }
        break;
    case 'c':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 't':
                return "catalan";
            case 'd':
                return "caddo";
            case 'i':
                return "central-american-indian";
            case 'r':
                return "galibi-carib";
            case 'u':
                return "caucasian";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
                return "chechen";
            case 'b':
                return "cebuano";
            case 'l':
                return "celtic";
            case 's':
                return "czech";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "chamorro";
            case 'b':
                return "chibcha";
            case 'e':
                return "chechen";
            case 'g':
                return "chagatai";
            case 'i':
                return "chinese";
            case 'k':
                return "chuukese";
            case 'm':
                return "mari";
            case 'n':
                return "chinook-jargon";
            case 'o':
                return "choctaw";
            case 'p':
                return "chipewyan";
            case 'r':
                return "cherokee";
            case 'u':
                return "church-slavic";
            case 'v':
                return "chuvash";
            case 'y':
                return "cheyenne";
            }
            break;
        case 'm':
            switch (c2)
            {
            case 'c':
                return "chamic";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 's':
                return "corsican";
            case 'p':
                return "coptic";
            case 'r':
                return "cornish";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'e':
                return "pidgin-english";
            case 'f':
                return "pidgin-french";
            case 'p':
                return "pidgin-portuguese";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "cree";
            case 'h':
                return "crimean-tatar";
            case 'p':
                return "creoles-and-pidgins";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
                return "czech";
            case 'b':
                return "kashubian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
                return "church-slavic";
            case 's':
                return "cushitic";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "chuvash";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "welsh";
            }
            break;
        case 'z':
            switch (c2)
            {
            case 'e':
                return "czech";
            }
            break;
        }
        break;
    case 'd':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "danish";
            case 'k':
                return "dakota";
            case 'r':
                return "dargwa";
            case 'y':
                return "land-dayak";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'u':
                return "german";
            case 'l':
                return "delaware";
            case 'n':
                return "slave";
            }
            break;
        case 'g':
            switch (c2)
            {
            case 'r':
                return "dogrib";
            }
            break;
        case 'i':
            switch (c2)
            {
            case 'n':
                return "dinka";
            case 'v':
                return "divehi";
            }
            break;
        case 'o':
            switch (c2)
            {
            case 'i':
                return "dogri";
            }
            break;
        case 'r':
            switch (c2)
            {
            case 'a':
                return "dravidian";
            }
            break;
        case 's':
            switch (c2)
            {
            case 'b':
                return "lower-sorbian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'a':
                return "duala";
            case 'm':
                return "middle-dutch";
            case 't':
                return "dutch";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "divehi";
            }
            break;
        case 'y':
            switch (c2)
            {
            case 'u':
                return "dyula";
            }
            break;
        case 'z':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "dzongkha";
            }
            break;
        }
        break;
    case 'e':
        switch (c1)
        {
        case 'e':
            switch (c2)
            {
            case '\0':
                return "ewe";
            }
            break;
        case 'f':
            switch (c2)
            {
            case 'i':
                return "efik";
            }
            break;
        case 'g':
            switch (c2)
            {
            case 'y':
                return "egyptian";
            }
            break;
        case 'k':
            switch (c2)
            {
            case 'a':
                return "ekajuk";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "modern-greek";
            case 'x':
                return "elamite";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
            case 'g':
                return "english";
            case 'm':
                return "middle-english";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
                return "esperanto";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'o':
                return "esperanto";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
                return "spanish";
            case 't':
                return "estonian";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "estonian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 's':
                return "basque";
            }
            break;
        case 'w':
            switch (c2)
            {
            case 'e':
                return "ewe";
            case 'o':
                return "ewondo";
            }
            break;
        }
        break;
    case 'f':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 's':
                return "persian";
            case 'n':
                return "fang";
            case 'o':
                return "faroese";
            case 't':
                return "fanti";
            }
            break;
        case 'f':
            switch (c2)
            {
            case '\0':
                return "fulah";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "finnish";
            case 'j':
                return "fijian";
            case 'l':
                return "filipino";
            case 'u':
                return "finno-ugrian";
            }
            break;
        case 'j':
            switch (c2)
            {
            case '\0':
                return "fijian";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
                return "faroese";
            case 'n':
                return "fon";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'a':
            case 'e':
                return "french";
            case 'm':
                return "middle-french";
            case 'o':
                return "old-french";
            case 'r':
                return "northern-frisian";
            case 's':
                return "eastern-frisian";
            case 'y':
                return "western-frisian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'l':
                return "fulah";
            case 'r':
                return "friulian";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
                return "western-frisian";
            }
            break;
        }
        break;
    case 'g':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
                return "irish";
            case 'a':
                return "ga";
            case 'y':
                return "gayo";
            }
            break;
        case 'b':
            switch (c2)
            {
            case 'a':
                return "gbaya";
            }
            break;
        case 'd':
            switch (c2)
            {
            case '\0':
                return "gaelic";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'm':
                return "germanic";
            case 'o':
                return "georgian";
            case 'r':
                return "german";
            case 'z':
                return "geez";
            }
            break;
        case 'i':
            switch (c2)
            {
            case 'l':
                return "gilbertese";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
            case 'g':
                return "galician";
            case 'a':
                return "gaelic";
            case 'e':
                return "irish";
            case 'v':
                return "manx";
            }
            break;
        case 'm':
            switch (c2)
            {
            case 'h':
                return "middle-high-german";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "guarani";
            }
            break;
        case 'o':
            switch (c2)
            {
            case 'h':
                return "old-high-german";
            case 'n':
                return "gondi";
            case 'r':
                return "gorontalo";
            case 't':
                return "gothic";
            }
            break;
        case 'r':
            switch (c2)
            {
            case 'b':
                return "grebo";
            case 'c':
                return "ancient-greek";
            case 'e':
                return "modern-greek";
            case 'n':
                return "guarani";
            }
            break;
        case 's':
            switch (c2)
            {
            case 'w':
                return "swiss-german";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'j':
                return "gujarati";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "manx";
            }
            break;
        case 'w':
            switch (c2)
            {
            case 'i':
                return "gwichin";
            }
            break;
        }
        break;
    case 'h':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'u':
                return "hausa";
            case 'i':
                return "haida";
            case 't':
                return "haitian";
            case 'w':
                return "hawaiian";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'b':
                return "hebrew";
            case 'r':
                return "herero";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "hindi";
            case 'l':
                return "hiligaynon";
            case 'm':
                return "himachali";
            case 't':
                return "hittite";
            }
            break;
        case 'm':
            switch (c2)
            {
            case 'n':
                return "hmong";
            case 'o':
                return "hiri-motu";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
                return "hiri-motu";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'v':
                return "croatian";
            }
            break;
        case 's':
            switch (c2)
            {
            case 'b':
                return "upper-sorbian";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "haitian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "hungarian";
            case 'p':
                return "hupa";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "armenian";
            }
            break;
        case 'z':
            switch (c2)
            {
            case '\0':
                return "herero";
            }
            break;
        }
        break;
    case 'i':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
                return "interlingua";
            }
            break;
        case 'b':
            switch (c2)
            {
            case 'a':
                return "iban";
            case 'o':
                return "igbo";
            }
            break;
        case 'c':
            switch (c2)
            {
            case 'e':
                return "icelandic";
            }
            break;
        case 'd':
            switch (c2)
            {
            case '\0':
                return "indonesian";
            case 'o':
                return "ido";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
                return "interlingue";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "igbo";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "sichuan-yi";
            }
            break;
        case 'j':
            switch (c2)
            {
            case 'o':
                return "ijo";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
                return "inupiaq";
            case 'u':
                return "inuktitut";
            }
            break;
        case 'l':
            switch (c2)
            {
            case 'e':
                return "interlingue";
            case 'o':
                return "iloko";
            }
            break;
        case 'n':
            switch (c2)
            {
            case 'a':
                return "interlingua";
            case 'c':
                return "indic";
            case 'd':
                return "indonesian";
            case 'e':
                return "indo-european";
            case 'h':
                return "ingush";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
                return "ido";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'k':
                return "inupiaq";
            }
            break;
        case 'r':
            switch (c2)
            {
            case 'a':
                return "iranian";
            case 'o':
                return "iroquoian";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "icelandic";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "italian";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
                return "inuktitut";
            }
            break;
        }
        break;
    case 'j':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
                return "japanese";
            case 'v':
                return "javanese";
            }
            break;
        case 'b':
            switch (c2)
            {
            case 'o':
                return "lojban";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'n':
                return "japanese";
            case 'r':
                return "judeo-persian";
            }
            break;
        case 'r':
            switch (c2)
            {
            case 'b':
                return "judeo-arabic";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "javanese";
            }
            break;
        }
        break;
    case 'k':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 't':
                return "georgian";
            case 'a':
                return "kara-kalpak";
            case 'b':
                return "kabyle";
            case 'c':
                return "kachin";
            case 'l':
                return "kalaallisut";
            case 'm':
                return "kamba";
            case 'n':
                return "kannada";
            case 'r':
                return "karen";
            case 's':
                return "kashmiri";
            case 'u':
                return "kanuri";
            case 'w':
                return "kawi";
            case 'z':
                return "kazakh";
            }
            break;
        case 'b':
            switch (c2)
            {
            case 'd':
                return "kabardian";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "kongo";
            }
            break;
        case 'h':
            switch (c2)
            {
            case 'a':
                return "khasi";
            case 'i':
                return "khoisan";
            case 'm':
                return "central-khmer";
            case 'o':
                return "khotanese";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'k':
                return "kikuyu";
            case 'n':
                return "kinyarwanda";
            case 'r':
                return "kirghiz";
            }
            break;
        case 'j':
            switch (c2)
            {
            case '\0':
                return "kuanyama";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
                return "kazakh";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
                return "kalaallisut";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
                return "central-khmer";
            case 'b':
                return "kimbundu";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "kannada";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "korean";
            case 'k':
                return "konkani";
            case 'm':
                return "komi";
            case 'n':
                return "kongo";
            case 's':
                return "kosraean";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'e':
                return "kpelle";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
                return "kanuri";
            case 'c':
                return "karachay-balkar";
            case 'l':
                return "karelian";
            case 'o':
                return "kru";
            case 'u':
                return "kurukh";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
                return "kashmiri";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "kurdish";
            case 'a':
                return "kuanyama";
            case 'm':
                return "kumyk";
            case 't':
                return "kutenai";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "komi";
            }
            break;
        case 'w':
            switch (c2)
            {
            case '\0':
                return "cornish";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
                return "kirghiz";
            }
            break;
        }
        break;
    case 'l':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 't':
                return "latin";
            case 'd':
                return "ladino";
            case 'h':
                return "lahnda";
            case 'm':
                return "lamba";
            case 'o':
                return "lao";
            case 'v':
                return "latvian";
            }
            break;
        case 'b':
            switch (c2)
            {
            case '\0':
                return "luxembourgish";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'z':
                return "lezghian";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "ganda";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "limburgan";
            case 'n':
                return "lingala";
            case 't':
                return "lithuanian";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "lingala";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
                return "lao";
            case 'l':
                return "mongo";
            case 'z':
                return "lozi";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "lithuanian";
            case 'z':
                return "luxembourgish";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'b':
                return "luba-katanga";
            case 'a':
                return "luba-lulua";
            case 'g':
                return "ganda";
            case 'i':
                return "luiseno";
            case 'n':
                return "lunda";
            case 'o':
                return "luo";
            case 's':
                return "lushai";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "latvian";
            }
            break;
        }
        break;
    case 'm':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case 'c':
                return "macedonian";
            case 'd':
                return "madurese";
            case 'g':
                return "magahi";
            case 'h':
                return "marshallese";
            case 'i':
                return "maithili";
            case 'k':
                return "makasar";
            case 'l':
                return "malayalam";
            case 'n':
                return "mandingo";
            case 'o':
                return "maori";
            case 'p':
                return "austronesian";
            case 'r':
                return "marathi";
            case 's':
                return "masai";
            case 'y':
                return "malay";
            }
            break;
        case 'd':
            switch (c2)
            {
            case 'f':
                return "moksha";
            case 'r':
                return "mandar";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'n':
                return "mende";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "malagasy";
            case 'a':
                return "middle-irish";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
                return "marshallese";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
                return "maori";
            case 'c':
                return "mikmaq";
            case 'n':
                return "minangkabau";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
            case 'd':
                return "macedonian";
            case 'h':
                return "mon-khmer";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
                return "malayalam";
            case 'g':
                return "malagasy";
            case 't':
                return "maltese";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "mongolian";
            case 'c':
                return "manchu";
            case 'i':
                return "manipuri";
            case 'o':
                return "manobo";
            }
            break;
        case 'o':
            switch (c2)
            {
            case 'h':
                return "mohawk";
            case 'n':
                return "mongolian";
            case 's':
                return "mossi";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
                return "marathi";
            case 'i':
                return "maori";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "malay";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "maltese";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'l':
                return "multiple";
            case 'n':
                return "munda";
            case 's':
                return "creek";
            }
            break;
        case 'w':
            switch (c2)
            {
            case 'l':
                return "mirandese";
            case 'r':
                return "marwari";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "burmese";
            case 'n':
                return "mayan";
            case 'v':
                return "erzya";
            }
            break;
        }
        break;
    case 'n':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'u':
                return "nauru";
            case 'h':
                return "nahuatl";
            case 'i':
                return "north-american-indian";
            case 'p':
                return "neapolitan";
            case 'v':
                return "navajo";
            }
            break;
        case 'b':
            switch (c2)
            {
            case '\0':
                return "norwegian-bokmal";
            case 'l':
                return "south-ndebele";
            }
            break;
        case 'd':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "north-ndebele";
            case 'o':
                return "ndonga";
            case 's':
                return "low-german";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'p':
                return "nepali";
            case 'w':
                return "nepal-bhasa";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "ndonga";
            }
            break;
        case 'i':
            switch (c2)
            {
            case 'a':
                return "nias";
            case 'c':
                return "niger-kordofanian";
            case 'u':
                return "niuean";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
            case 'd':
                return "dutch";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "norwegian-nynorsk";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "norwegian";
            case 'b':
                return "norwegian-bokmal";
            case 'g':
                return "nogai";
            case 'n':
                return "old-norse";
            }
            break;
        case 'q':
            switch (c2)
            {
            case 'o':
                return "nko";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
                return "south-ndebele";
            }
            break;
        case 's':
            switch (c2)
            {
            case 'o':
                return "pedi";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'b':
                return "nubian";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "navajo";
            }
            break;
        case 'w':
            switch (c2)
            {
            case 'c':
                return "classical-newari";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "chichewa";
            case 'm':
                return "nyamwezi";
            case 'n':
                return "nyankole";
            case 'o':
                return "nyoro";
            }
            break;
        case 'z':
            switch (c2)
            {
            case 'i':
                return "nzima";
            }
            break;
        }
        break;
    case 'o':
        switch (c1)
        {
        case 'c':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "occitan";
            }
            break;
        case 'j':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "ojibwa";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
                return "oromo";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "oriya";
            case 'm':
                return "oromo";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 's':
                return "ossetian";
            case 'a':
                return "osage";
            }
            break;
        case 't':
            switch (c2)
            {
            case 'a':
                return "ottoman-turkish";
            case 'o':
                return "otomian";
            }
            break;
        }
        break;
    case 'p':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "panjabi";
            case 'a':
                return "papuan";
            case 'g':
                return "pangasinan";
            case 'l':
                return "pahlavi";
            case 'm':
                return "pampanga";
            case 'p':
                return "papiamento";
            case 'u':
                return "palauan";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'o':
                return "old-persian";
            case 'r':
                return "persian";
            }
            break;
        case 'h':
            switch (c2)
            {
            case 'i':
                return "philippine";
            case 'n':
                return "phoenician";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
                return "pali";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
                return "polish";
            case 'i':
                return "pali";
            }
            break;
        case 'o':
            switch (c2)
            {
            case 'l':
                return "polish";
            case 'n':
                return "pohnpeian";
            case 'r':
                return "portuguese";
            }
            break;
        case 'r':
            switch (c2)
            {
            case 'a':
                return "prakrit";
            case 'o':
                return "old-provencal";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
                return "pushto";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "portuguese";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 's':
                return "pushto";
            }
            break;
        }
        break;
    case 'q':
        switch (c1)
        {
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "quechua";
            }
            break;
        }
        break;
    case 'r':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case 'j':
                return "rajasthani";
            case 'p':
                return "rapanui";
            case 'r':
                return "rarotongan";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
                return "romansh";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "rundi";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "romanian";
            case 'a':
                return "romance";
            case 'h':
                return "romansh";
            case 'm':
                return "romany";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 's':
                return "russian";
            case 'm':
                return "romanian";
            case 'n':
                return "rundi";
            case 'p':
                return "aromanian";
            }
            break;
        case 'w':
            switch (c2)
            {
            case '\0':
                return "kinyarwanda";
            }
            break;
        }
        break;
    case 's':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "sanskrit";
            case 'd':
                return "sandawe";
            case 'g':
                return "sango";
            case 'h':
                return "yakut";
            case 'i':
                return "south-american-indian";
            case 'l':
                return "salishan";
            case 'm':
                return "samaritan-aramaic";
            case 's':
                return "sasak";
            case 't':
                return "santali";
            }
            break;
        case 'c':
            switch (c2)
            {
            case '\0':
                return "sardinian";
            case 'n':
                return "sicilian";
            case 'o':
                return "scots";
            }
            break;
        case 'd':
            switch (c2)
            {
            case '\0':
                return "sindhi";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
                return "northern-sami";
            case 'l':
                return "selkup";
            case 'm':
                return "semitic";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "sango";
            case 'a':
                return "old-irish";
            case 'n':
                return "sign-languages";
            }
            break;
        case 'h':
            switch (c2)
            {
            case 'n':
                return "shan";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "sinhala";
            case 'd':
                return "sidamo";
            case 'o':
                return "siouan";
            case 't':
                return "sino-tibetan";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
                return "slovak";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
            case 'v':
                return "slovenian";
            case 'a':
                return "slavic";
            case 'k':
            case 'o':
                return "slovak";
            }
            break;
        case 'm':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "samoan";
            case 'a':
                return "southern-sami";
            case 'e':
                return "northern-sami";
            case 'i':
                return "sami";
            case 'j':
                return "lule-sami";
            case 'n':
                return "inari-sami";
            case 's':
                return "skolt-sami";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "shona";
            case 'd':
                return "sindhi";
            case 'k':
                return "soninke";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "somali";
            case 'g':
                return "sogdian";
            case 'n':
                return "songhai";
            case 't':
                return "southern-sotho";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'a':
                return "spanish";
            }
            break;
        case 'q':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "albanian";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'p':
                return "serbian";
            case 'd':
                return "sardinian";
            case 'n':
                return "sranan-tongo";
            case 'r':
                return "serer";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 'w':
                return "swati";
            case 'a':
                return "nilo-saharan";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "southern-sotho";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "sundanese";
            case 'k':
                return "sukuma";
            case 's':
                return "susu";
            case 'x':
                return "sumerian";
            }
            break;
        case 'v':
            switch (c2)
            {
            case '\0':
                return "swedish";
            }
            break;
        case 'w':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "swahili";
            case 'e':
                return "swedish";
            }
            break;
        case 'y':
            switch (c2)
            {
            case 'c':
                return "classical-syriac";
            case 'r':
                return "syriac";
            }
            break;
        }
        break;
    case 't':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
            case 'm':
                return "tamil";
            case 'h':
                return "tahitian";
            case 'i':
                return "tai";
            case 't':
                return "tatar";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "telugu";
            case 'm':
                return "timne";
            case 'r':
                return "tereno";
            case 't':
                return "tetum";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
            case 'k':
                return "tajik";
            case 'l':
                return "tagalog";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
            case 'a':
                return "thai";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "tigrinya";
            case 'b':
                return "tibetan";
            case 'g':
                return "tigre";
            case 'v':
                return "tiv";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
                return "turkmen";
            case 'l':
                return "tokelau";
            }
            break;
        case 'l':
            switch (c2)
            {
            case '\0':
                return "tagalog";
            case 'h':
                return "klingon";
            case 'i':
                return "tlingit";
            }
            break;
        case 'm':
            switch (c2)
            {
            case 'h':
                return "tamashek";
            }
            break;
        case 'n':
            switch (c2)
            {
            case '\0':
                return "tswana";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "tongan";
            case 'g':
                return "tonga";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'i':
                return "tok-pisin";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
                return "turkish";
            }
            break;
        case 's':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "tsonga";
            case 'i':
                return "tsimshian";
            case 'n':
                return "tswana";
            }
            break;
        case 't':
            switch (c2)
            {
            case '\0':
                return "tatar";
            }
            break;
        case 'u':
            switch (c2)
            {
            case 'k':
                return "turkmen";
            case 'm':
                return "tumbuka";
            case 'p':
                return "tupi";
            case 'r':
                return "turkish";
            case 't':
                return "altaic";
            }
            break;
        case 'v':
            switch (c2)
            {
            case 'l':
                return "tuvalu";
            }
            break;
        case 'w':
            switch (c2)
            {
            case '\0':
            case 'i':
                return "twi";
            }
            break;
        case 'y':
            switch (c2)
            {
            case '\0':
                return "tahitian";
            case 'v':
                return "tuvinian";
            }
            break;
        }
        break;
    case 'u':
        switch (c1)
        {
        case 'd':
            switch (c2)
            {
            case 'm':
                return "udmurt";
            }
            break;
        case 'g':
            switch (c2)
            {
            case '\0':
                return "uighur";
            case 'a':
                return "ugaritic";
            }
            break;
        case 'i':
            switch (c2)
            {
            case 'g':
                return "uighur";
            }
            break;
        case 'k':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "ukrainian";
            }
            break;
        case 'm':
            switch (c2)
            {
            case 'b':
                return "umbundu";
            }
            break;
        case 'r':
            switch (c2)
            {
            case '\0':
            case 'd':
                return "urdu";
            }
            break;
        case 'z':
            switch (c2)
            {
            case '\0':
            case 'b':
                return "uzbek";
            }
            break;
        }
        break;
    case 'v':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case 'i':
                return "vai";
            }
            break;
        case 'e':
            switch (c2)
            {
            case '\0':
            case 'n':
                return "venda";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'e':
                return "vietnamese";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "volapuk";
            case 't':
                return "votic";
            }
            break;
        }
        break;
    case 'w':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
                return "walloon";
            case 'k':
                return "wakashan";
            case 'l':
                return "walamo";
            case 'r':
                return "waray";
            case 's':
                return "washo";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'l':
                return "welsh";
            case 'n':
                return "sorbian";
            }
            break;
        case 'l':
            switch (c2)
            {
            case 'n':
                return "walloon";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "wolof";
            }
            break;
        }
        break;
    case 'x':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case 'l':
                return "kalmyk";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "xhosa";
            }
            break;
        }
        break;
    case 'y':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case 'o':
                return "yao";
            case 'p':
                return "yapese";
            }
            break;
        case 'i':
            switch (c2)
            {
            case '\0':
            case 'd':
                return "yiddish";
            }
            break;
        case 'o':
            switch (c2)
            {
            case '\0':
            case 'r':
                return "yoruba";
            }
            break;
        case 'p':
            switch (c2)
            {
            case 'k':
                return "yupik";
            }
            break;
        }
        break;
    case 'z':
        switch (c1)
        {
        case 'a':
            switch (c2)
            {
            case '\0':
                return "zhuang";
            case 'p':
                return "zapotec";
            }
            break;
        case 'b':
            switch (c2)
            {
            case 'l':
                return "blissymbols";
            }
            break;
        case 'e':
            switch (c2)
            {
            case 'n':
                return "zenaga";
            }
            break;
        case 'h':
            switch (c2)
            {
            case '\0':
            case 'o':
                return "chinese";
            case 'a':
                return "zhuang";
            }
            break;
        case 'n':
            switch (c2)
            {
            case 'd':
                return "zande";
            }
            break;
        case 'u':
            switch (c2)
            {
            case '\0':
            case 'l':
                return "zulu";
            case 'n':
                return "zuni";
            }
            break;
        case 'z':
            switch (c2)
            {
            case 'a':
                return "zaza";
            }
            break;
        }
        break;
    }
    return NULL;
}
