#include "registry.h"
#include "qpils_event.h"
#include "qpils_supplement.h"
#include "qpils_clang.h"
namespace PILS
{
void QtObjectClassName::initialize()
{
    BEGIN_CLASS(QObject)
    CONSTRUCTOR_NOARGS(QObject)
    CONSTRUCTOR_ARGS(QObject, QObject*)
    BLIND_SIGNAL(QObject, destroyed)
    END_CLASS()

    BEGIN_CLASS(QPilsCloseChildren)
    CONSTRUCTOR_NOARGS(QPilsCloseChildren)
    END_CLASS()

    BEGIN_CLASS(QApplication)
    SIGNAL_(QApplication, focusChanged)
    SIGNAL_(QApplication, applicationStateChanged)
    SIGNAL_(QApplication, aboutToQuit)
    END_CLASS()
    // const QtObjectClassName* classEntry = nullptr;

    // ===== QWidget =====
    BEGIN_CLASS(QWidget)
    CONSTRUCTOR_NOARGS(QWidget)
    CONSTRUCTOR_ARGS(QWidget, QWidget*)
    // QWidget basics
    METHOD_(QWidget, show)
    METHOD_(QWidget, hide)
    METHOD_(QWidget, close)
    METHOD_OVERLOAD(QWidget, update, void(QWidget::*)())
    METHOD_OVERLOAD(QWidget, repaint, void(QWidget::*)())
    METHOD_(QWidget, width)
    METHOD_(QWidget, height)
    METHOD_(QWidget, size)
    METHOD_(QWidget, pos)
    METHOD_(QWidget, setWindowTitle)
    METHOD_(QWidget, setEnabled)
    METHOD_(QWidget, isEnabled)
    METHOD_(QWidget, setVisible)
    METHOD_(QWidget, isVisible)
    METHOD_(QWidget, setStyleSheet)
    METHOD_(QWidget, setWindowIcon)
    METHOD_OVERLOAD(QWidget, setFocus, void(QWidget::*)())
    METHOD_OVERLOAD(QWidget, resize, void(QWidget::*)(int,int))
    // METHOD_OVERLOAD(QWidget, resize, void(QWidget::*)(const QSize&))
    METHOD_OVERLOAD(QWidget, move, void(QWidget::*)(int,int))
    METHOD_OVERLOAD(QWidget, setGeometry, void(QWidget::*)(int,int,int,int))
    METHOD_(QWidget, setAttribute)
    // Layout-ish
    METHOD_(QWidget, setLayout)
    METHOD_(QWidget, layout)
    // QWidget ekstra
    METHOD_(QWidget, raise)
    METHOD_(QWidget, lower)
    METHOD_(QWidget, activateWindow)
    METHOD_OVERLOAD(QWidget, setMinimumSize, void(QWidget::*)(int,int))
    METHOD_OVERLOAD(QWidget, setMaximumSize, void(QWidget::*)(int,int))
    METHOD_OVERLOAD(QWidget, setFixedSize, void(QWidget::*)(int,int))
    METHOD_(QWidget, setToolTip)
    // Layout helpers
    METHOD_OVERLOAD(QWidget, setParent, void(QWidget::*)(QWidget*))
    SIGNAL_(QWidget, customContextMenuRequested)
    SIGNAL_(QWidget, windowTitleChanged)
    SIGNAL_(QWidget, windowIconChanged)
    SIGNAL_(QWidget, windowIconTextChanged)
    SIGNAL_(QWidget, destroyed)
    SIGNAL_(QWidget, customContextMenuRequested)
    SIGNAL_(QWidget, windowTitleChanged)
    SIGNAL_(QWidget, windowIconChanged)
    SIGNAL_(QWidget, windowIconTextChanged)
    SIGNAL_(QWidget, destroyed)
    // visibility / lifecycle
    SIGNAL_(QWidget, show)
    SIGNAL_(QWidget, hide)
    METHOD_(QWidget, raise)
    METHOD_(QWidget, lower)
    METHOD_(QWidget, activateWindow)
    END_CLASS()

    BEGIN_CLASS(QWindow)
    SIGNAL_(QWindow, visibleChanged)
    SIGNAL_(QWindow, widthChanged)
    SIGNAL_(QWindow, heightChanged)
    SIGNAL_(QWindow, xChanged)
    SIGNAL_(QWindow, yChanged)
    END_CLASS()

    // ===== QMainWindow =====
    BEGIN_CLASS(QMainWindow)
    CONSTRUCTOR_NOARGS(QMainWindow)
    CONSTRUCTOR_ARGS(QMainWindow, QWidget*)
    METHOD_(QMainWindow, setCentralWidget)
    METHOD_(QMainWindow, centralWidget)
    METHOD_(QMainWindow, menuBar)
    METHOD_(QMainWindow, statusBar)
    METHOD_OVERLOAD(QMainWindow, addToolBar, QToolBar*(QMainWindow::*)(const QString&))

    SIGNAL_(QMainWindow, iconSizeChanged)
    SIGNAL_(QMainWindow, toolButtonStyleChanged)
    SIGNAL_(QMainWindow, tabifiedDockWidgetActivated)
    END_CLASS()

    // ===== QDialog =====
    BEGIN_CLASS(QDialog)
    CONSTRUCTOR_NOARGS(QDialog)
    CONSTRUCTOR_ARGS(QDialog, QWidget*)
    METHOD_(QDialog, exec)
    METHOD_(QDialog, accept)
    METHOD_(QDialog, reject)
    METHOD_(QDialog, setWindowModality)
    END_CLASS()

    // ===== QPushButton =====
    BEGIN_CLASS(QPushButton)
    CONSTRUCTOR_NOARGS(QPushButton)
    CONSTRUCTOR_ARGS(QPushButton, QWidget*)
    CONSTRUCTOR_ARGS(QPushButton, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QPushButton, const QString&)
    METHOD_(QPushButton, setText)
    METHOD_(QPushButton, text)
    METHOD_(QPushButton, setEnabled)
    METHOD_(QPushButton, click)
    SIGNAL_(QPushButton, clicked)
    SIGNAL_(QPushButton, pressed)
    SIGNAL_(QPushButton, released)
    SIGNAL_(QPushButton, toggled)
    END_CLASS()

    // ===== QToolButton =====
    BEGIN_CLASS(QToolButton)
    CONSTRUCTOR_NOARGS(QToolButton)
    CONSTRUCTOR_ARGS(QToolButton, QWidget*)
    END_CLASS()

    // ===== QCheckBox =====
    BEGIN_CLASS(QCheckBox)
    CONSTRUCTOR_NOARGS(QCheckBox)
    CONSTRUCTOR_ARGS(QCheckBox, QWidget*)
    CONSTRUCTOR_ARGS(QCheckBox, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QCheckBox, const QString&)
    METHOD_(QCheckBox, setChecked)
    METHOD_(QCheckBox, isChecked)
    SIGNAL_(QCheckBox, checkStateChanged)
    SIGNAL_(QCheckBox, toggled)
    END_CLASS()

    // ===== QRadioButton =====
    BEGIN_CLASS(QRadioButton)
    CONSTRUCTOR_NOARGS(QRadioButton)
    CONSTRUCTOR_ARGS(QRadioButton, QWidget*)
    CONSTRUCTOR_ARGS(QRadioButton, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QRadioButton, const QString&)
    METHOD_(QRadioButton, setChecked)
    METHOD_(QRadioButton, isChecked)
    SIGNAL_(QRadioButton, toggled)
    END_CLASS()

    // ===== QComboBox =====
    BEGIN_CLASS(QComboBox)
    CONSTRUCTOR_NOARGS(QComboBox)
    CONSTRUCTOR_ARGS(QComboBox, QWidget*)
    METHOD_OVERLOAD(QComboBox, addItem, void(QComboBox::*)(const QString&, const QVariant&))
    METHOD_(QComboBox, currentText)
    METHOD_(QComboBox, setCurrentIndex)
    METHOD_(QComboBox, currentIndex)
    SIGNAL_(QComboBox, currentIndexChanged)
    SIGNAL_(QComboBox, currentTextChanged)
    SIGNAL_(QComboBox, activated)
    SIGNAL_(QComboBox, highlighted)
    SIGNAL_(QComboBox, editTextChanged)
    END_CLASS()

    // ===== QLineEdit =====
    BEGIN_CLASS(QLineEdit)
    CONSTRUCTOR_NOARGS(QLineEdit)
    CONSTRUCTOR_ARGS(QLineEdit, QWidget*)
    CONSTRUCTOR_ARGS(QLineEdit, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QLineEdit, const QString&)
    METHOD_(QLineEdit, setText)
    METHOD_(QLineEdit, text)
    METHOD_(QLineEdit, clear)
    METHOD_(QLineEdit, setPlaceholderText)
    SIGNAL_(QLineEdit, textChanged)
    SIGNAL_(QLineEdit, textEdited)
    SIGNAL_(QLineEdit, returnPressed)
    SIGNAL_(QLineEdit, editingFinished)
    SIGNAL_(QLineEdit, cursorPositionChanged)
    SIGNAL_(QLineEdit, selectionChanged)
    END_CLASS()

    // ===== QTextEdit =====
    BEGIN_CLASS(QTextEdit)
    CONSTRUCTOR_NOARGS(QTextEdit)
    CONSTRUCTOR_ARGS(QTextEdit, QWidget*)
    CONSTRUCTOR_ARGS(QTextEdit, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QTextEdit, const QString&)
    METHOD_(QTextEdit, setText)
    METHOD_(QTextEdit, toPlainText)
    METHOD_(QTextEdit, setHtml)
    METHOD_(QTextEdit, toHtml)
    METHOD_(QTextEdit, clear)
    SIGNAL_(QTextEdit, textChanged)
    SIGNAL_(QTextEdit, cursorPositionChanged)
    SIGNAL_(QTextEdit, selectionChanged)
    END_CLASS()

    // ===== QPlainTextEdit =====
    BEGIN_CLASS(QPlainTextEdit)
    CONSTRUCTOR_NOARGS(QPlainTextEdit)
    CONSTRUCTOR_ARGS(QPlainTextEdit, QWidget*)
    CONSTRUCTOR_ARGS(QPlainTextEdit, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QPlainTextEdit, const QString&)
    METHOD_(QPlainTextEdit, setPlainText)
    METHOD_(QPlainTextEdit, toPlainText)
    METHOD_(QPlainTextEdit, appendPlainText)
    METHOD_(QPlainTextEdit, clear)
    METHOD_(QPlainTextEdit, setReadOnly)
    METHOD_(QPlainTextEdit, centerCursor)
    METHOD_(QPlainTextEdit, ensureCursorVisible)
    // METHOD_(QPlainTextEdit, textCursor)
    // METHOD_(QPlainTextEdit, setTextCursor)
    SIGNAL_(QPlainTextEdit, textChanged)
    SIGNAL_(QPlainTextEdit, cursorPositionChanged)
    SIGNAL_(QPlainTextEdit, selectionChanged)
    SIGNAL_(QPlainTextEdit, updateRequest)
    SIGNAL_(QPlainTextEdit, blockCountChanged)
    END_CLASS()

    // ===== QPilsPlainTextEdit =====
    BEGIN_CLASS(QPilsPlainTextEdit)
    CONSTRUCTOR_NOARGS(QPilsPlainTextEdit)
    // CONSTRUCTOR_ARGS(QPilsPlainTextEdit, QWidget*)
    // CONSTRUCTOR_ARGS(QPilsPlainTextEdit, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QPilsPlainTextEdit, const QString&)
    EXACT_METHOD(QPilsPlainTextEdit, selection)
    EXACT_METHOD(QPilsPlainTextEdit, setSelection)
    EXACT_METHOD(QPilsPlainTextEdit, selection_utf16)
    EXACT_METHOD(QPilsPlainTextEdit, setSelection_utf16)
    END_CLASS()

    // ===== QLabel =====
    BEGIN_CLASS(QLabel)
    CONSTRUCTOR_NOARGS(QLabel)
    CONSTRUCTOR_ARGS(QLabel, QWidget*)
    CONSTRUCTOR_ARGS(QLabel, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QLabel, const QString&)
    METHOD_(QLabel, setText)
    METHOD_(QLabel, text)
    METHOD_(QLabel, setPixmap)
    END_CLASS()

    // ===== QProgressBar =====
    BEGIN_CLASS(QProgressBar)
    CONSTRUCTOR_NOARGS(QProgressBar)
    CONSTRUCTOR_ARGS(QProgressBar, QWidget*)
    METHOD_(QProgressBar, setValue)
    METHOD_(QProgressBar, value)
    METHOD_(QProgressBar, setRange)
    END_CLASS()

    // ===== QSlider =====
    BEGIN_CLASS(QSlider)
    CONSTRUCTOR_NOARGS(QSlider)
    CONSTRUCTOR_ARGS(QSlider, QWidget*)
    CONSTRUCTOR_ARGS(QSlider, Qt::Orientation, QWidget*)
    CONSTRUCTOR_ARGS(QSlider, Qt::Orientation)
    SIGNAL_(QSlider, valueChanged)
    SIGNAL_(QSlider, sliderPressed)
    SIGNAL_(QSlider, sliderReleased)
    SIGNAL_(QSlider, sliderMoved)
    END_CLASS()

    // ===== QSpinBox =====
    BEGIN_CLASS(QSpinBox)
    CONSTRUCTOR_NOARGS(QSpinBox)
    CONSTRUCTOR_ARGS(QSpinBox, QWidget*)
    SIGNAL_(QSpinBox, valueChanged)
    END_CLASS()

    // ===== QDoubleSpinBox =====
    BEGIN_CLASS(QDoubleSpinBox)
    CONSTRUCTOR_NOARGS(QDoubleSpinBox)
    CONSTRUCTOR_ARGS(QDoubleSpinBox, QWidget*)
    SIGNAL_(QDoubleSpinBox, valueChanged)
    END_CLASS()

    // ===== QTabWidget =====
    BEGIN_CLASS(QTabWidget)
    CONSTRUCTOR_NOARGS(QTabWidget)
    CONSTRUCTOR_ARGS(QTabWidget, QWidget*)
    METHOD_OVERLOAD(QTabWidget, addTab, int(QTabWidget::*)(QWidget*, const QString&))
    METHOD_(QTabWidget, setCurrentIndex)
    METHOD_(QTabWidget, currentIndex)
    METHOD_(QTabWidget, count)
    METHOD_(QTabWidget, widget)
    METHOD_(QTabWidget, removeTab)
    METHOD_(QTabWidget, setTabText)
    METHOD_(QTabWidget, tabText)
    METHOD_(QTabWidget, setTabsClosable)
    METHOD_(QTabWidget, currentWidget)   // bekvemmelighed
    METHOD_(QTabWidget, setCurrentWidget)   // bekvemmelighed
    SIGNAL_(QTabWidget, currentChanged)
    SIGNAL_(QTabWidget, tabCloseRequested)
    SIGNAL_(QTabWidget, tabBarClicked)
    SIGNAL_(QTabWidget, tabBarDoubleClicked)
    END_CLASS()

    // ===== QSplitter =====
    BEGIN_CLASS(QSplitter)
    CONSTRUCTOR_NOARGS(QSplitter)
    CONSTRUCTOR_ARGS(QSplitter, QWidget*)
    CONSTRUCTOR_ARGS(QSplitter, Qt::Orientation, QWidget*)
    CONSTRUCTOR_ARGS(QSplitter, Qt::Orientation)
    METHOD_(QSplitter, addWidget)
    METHOD_(QSplitter, setOrientation)
    METHOD_(QSplitter, setSizes)
    SIGNAL_(QSplitter, splitterMoved)
    END_CLASS()

    // ===== QMenu =====
    BEGIN_CLASS(QMenu)
    CONSTRUCTOR_NOARGS(QMenu)
    CONSTRUCTOR_ARGS(QMenu, QWidget*)
    CONSTRUCTOR_ARGS(QMenu, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QMenu, const QString&)
    METHOD_OVERLOAD(QMenu, addAction, QAction*(QMenu::*)(const QString&))
    METHOD_(QMenu, addSeparator)
    METHOD_OVERLOAD(QMenu, addMenu, QMenu*(QMenu::*)(const QString&))
    METHOD_(QMenu, clear)
    SIGNAL_(QMenu, triggered)
    SIGNAL_(QMenu, hovered)
    SIGNAL_(QMenu, aboutToShow)
    SIGNAL_(QMenu, aboutToHide)
    END_CLASS()

    // ===== QAction =====
    BEGIN_CLASS(QAction)
    CONSTRUCTOR_NOARGS(QAction)
    CONSTRUCTOR_ARGS(QAction, QObject*)
    CONSTRUCTOR_ARGS(QAction, const QString&, QObject*)
    CONSTRUCTOR_ARGS(QAction, const QString&)
    METHOD_(QAction, setEnabled)
    METHOD_(QAction, isEnabled)
    METHOD_(QAction, setVisible)
    METHOD_(QAction, isVisible)
    METHOD_(QAction, setText)
    METHOD_(QAction, text)
    METHOD_(QAction, setCheckable)
    METHOD_(QAction, isCheckable)
    METHOD_(QAction, setChecked)
    METHOD_(QAction, isChecked)
    METHOD_(QAction, setShortcut)
    SIGNAL_(QAction, triggered)
    SIGNAL_(QAction, toggled)
    SIGNAL_(QAction, hovered)
    SIGNAL_(QAction, changed)
    END_CLASS()

    // ===== QFileDialog =====
    BEGIN_CLASS(QFileDialog)
    CONSTRUCTOR_NOARGS(QFileDialog)
    CONSTRUCTOR_ARGS(QFileDialog, QWidget*)
    CONSTRUCTOR_ARGS(QFileDialog, QWidget*, const QString&)
    CONSTRUCTOR_ARGS(QFileDialog, QWidget*, const QString&, const QString&)
    METHOD_(QFileDialog, setFileMode)
    METHOD_(QFileDialog, setNameFilter)
    METHOD_OVERLOAD(QFileDialog, setDirectory, void(QFileDialog::*)(const QString &))
    METHOD_(QFileDialog, selectedFiles)
    SIGNAL_(QFileDialog, fileSelected)
    END_CLASS()

    // ===== QMessageBox =====
    BEGIN_CLASS(QMessageBox)
    CONSTRUCTOR_NOARGS(QMessageBox)
    CONSTRUCTOR_ARGS(QMessageBox, QWidget*)
    METHOD_(QMessageBox, setText)
    METHOD_(QMessageBox, exec)
    END_CLASS()

    // ===== Views =====
    BEGIN_CLASS(QListView)
    CONSTRUCTOR_NOARGS(QListView)
    CONSTRUCTOR_ARGS(QListView, QWidget*)
    SIGNAL_(QListView, clicked)
    SIGNAL_(QListView, doubleClicked)
    SIGNAL_(QListView, activated)
    END_CLASS()

    BEGIN_CLASS(QTreeView)
    CONSTRUCTOR_NOARGS(QTreeView)
    CONSTRUCTOR_ARGS(QTreeView, QWidget*)
    SIGNAL_(QTreeView, clicked)
    SIGNAL_(QTreeView, doubleClicked)
    SIGNAL_(QTreeView, expanded)
    SIGNAL_(QTreeView, collapsed)
    END_CLASS()

    BEGIN_CLASS(QTableView)
    CONSTRUCTOR_NOARGS(QTableView)
    CONSTRUCTOR_ARGS(QTableView, QWidget*)
    END_CLASS()

    // ===== Layouts =====
    BEGIN_CLASS(QLayout)
    METHOD_(QLayout, addWidget)
    METHOD_(QLayout, setSpacing)
    METHOD_OVERLOAD(QLayout, setContentsMargins, void(QLayout::*)(int,int,int,int))
    END_CLASS()

    BEGIN_CLASS(QBoxLayout)
    METHOD_OVERLOAD(QBoxLayout, addWidget, void(QBoxLayout::*)(QWidget*, int, Qt::Alignment))
    END_CLASS()

    BEGIN_CLASS(QVBoxLayout)
    CONSTRUCTOR_NOARGS(QVBoxLayout)
    CONSTRUCTOR_ARGS(QVBoxLayout, QWidget*)
    METHOD_(QVBoxLayout, addWidget)
    METHOD_OVERLOAD(QVBoxLayout, addWidget, void(QVBoxLayout::*)(QWidget*, int, Qt::Alignment))
    END_CLASS()

    BEGIN_CLASS(QHBoxLayout)
    CONSTRUCTOR_NOARGS(QHBoxLayout)
    CONSTRUCTOR_ARGS(QHBoxLayout, QWidget*)
    METHOD_(QHBoxLayout, addWidget)
    METHOD_OVERLOAD(QHBoxLayout, addWidget, void(QHBoxLayout::*)(QWidget*, int, Qt::Alignment))
    END_CLASS()

    BEGIN_CLASS(QGridLayout)
    CONSTRUCTOR_NOARGS(QGridLayout)
    CONSTRUCTOR_ARGS(QGridLayout, QWidget*)
    END_CLASS()

    BEGIN_CLASS(QMenuBar)
    CONSTRUCTOR_NOARGS(QMenuBar)
    CONSTRUCTOR_ARGS(QMenuBar, QWidget*)
    METHOD_OVERLOAD(QMenuBar, addMenu, QMenu*(QMenuBar::*)(const QString&))
    METHOD_OVERLOAD(QMenuBar, addAction, QAction*(QMenuBar::*)(const QString&))
    METHOD_(QMenuBar, clear)
    END_CLASS()

    BEGIN_CLASS(QStatusBar)
    CONSTRUCTOR_NOARGS(QStatusBar)
    CONSTRUCTOR_ARGS(QStatusBar, QWidget*)
    METHOD_OVERLOAD(QStatusBar, addWidget, void(QStatusBar::*)(QWidget*, int))
    METHOD_OVERLOAD(QStatusBar, addPermanentWidget, void(QStatusBar::*)(QWidget*, int))
    METHOD_(QStatusBar, removeWidget)
    METHOD_OVERLOAD(QStatusBar, showMessage, void(QStatusBar::*)(const QString&, int))
    METHOD_(QStatusBar, clearMessage)
    METHOD_(QStatusBar, currentMessage)
    END_CLASS()

    BEGIN_CLASS(QScrollArea)
    CONSTRUCTOR_NOARGS(QScrollArea)
    CONSTRUCTOR_ARGS(QScrollArea, QWidget*)
    METHOD_(QScrollArea, setWidget)
    METHOD_(QScrollArea, widget)
    METHOD_(QScrollArea, setWidgetResizable)
    END_CLASS()

    BEGIN_CLASS(QScrollBar)
    SIGNAL_(QScrollBar, valueChanged)
    SIGNAL_(QScrollBar, sliderMoved)
    SIGNAL_(QScrollBar, rangeChanged)
    END_CLASS()

    BEGIN_CLASS(QFrame)
    CONSTRUCTOR_NOARGS(QFrame)
    CONSTRUCTOR_ARGS(QFrame, QWidget*)
    METHOD_(QFrame, setFrameShape)
    METHOD_(QFrame, frameShape)
    METHOD_(QFrame, setFrameShadow)
    METHOD_(QFrame, frameShadow)
    METHOD_(QFrame, setFrameStyle)
    METHOD_(QFrame, frameStyle)
    METHOD_(QFrame, setLineWidth)
    METHOD_(QFrame, lineWidth)
    METHOD_(QFrame, setMidLineWidth)
    METHOD_(QFrame, midLineWidth)
    METHOD_(QFrame, frameWidth)
    END_CLASS()

    BEGIN_CLASS(QGroupBox)
    CONSTRUCTOR_NOARGS(QGroupBox)
    CONSTRUCTOR_ARGS(QGroupBox, QWidget*)
    CONSTRUCTOR_ARGS(QGroupBox, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QGroupBox, const QString&)
    METHOD_(QGroupBox, setFlat)
    METHOD_(QGroupBox, isFlat)
    METHOD_(QGroupBox, setAlignment)
    METHOD_(QGroupBox, alignment)
    METHOD_(QGroupBox, setCheckable)
    METHOD_(QGroupBox, isCheckable)
    METHOD_(QGroupBox, setChecked)
    METHOD_(QGroupBox, isChecked)
    METHOD_(QGroupBox, title)
    METHOD_(QGroupBox, setTitle)
    END_CLASS()

    BEGIN_CLASS(QPilsGroupBox)
    CONSTRUCTOR_NOARGS(QPilsGroupBox)
    CONSTRUCTOR_ARGS(QPilsGroupBox, QWidget*)
    CONSTRUCTOR_ARGS(QPilsGroupBox, const QString&, QWidget*)
    CONSTRUCTOR_ARGS(QPilsGroupBox, const QString&)
    END_CLASS()

    BEGIN_CLASS(QTabBar)
    CONSTRUCTOR_NOARGS(QTabBar)
    CONSTRUCTOR_ARGS(QTabBar, QWidget*)
    END_CLASS()

    BEGIN_CLASS(QPilsTreeWidget)
    SIGNAL_(QTreeWidget, itemActivated)
    END_CLASS()

    BEGIN_CLASS(QPilsTreeWidget)
    CONSTRUCTOR_NOARGS(QPilsTreeWidget)
    CONSTRUCTOR_ARGS(QPilsTreeWidget, QWidget*)
    EXACT_METHOD(QPilsTreeWidget, addRootNode)
    EXACT_METHOD(QPilsTreeWidget, currentNode)
    EXACT_METHOD(QPilsTreeWidget, clearTree)
    END_CLASS()

    BEGIN_CLASS(QPilsTreeNode)
    EXACT_METHOD(QPilsTreeNode, text)
    EXACT_METHOD(QPilsTreeNode, setText)
    EXACT_METHOD(QPilsTreeNode, addChild)
    EXACT_METHOD(QPilsTreeNode, parentNode)
    EXACT_METHOD(QPilsTreeNode, childCount)
    EXACT_METHOD(QPilsTreeNode, child)
    EXACT_METHOD(QPilsTreeNode, expand)
    EXACT_METHOD(QPilsTreeNode, collapse)
    END_CLASS()

    BEGIN_CLASS(QShortcut)
    CONSTRUCTOR_ARGS(QShortcut, QKeySequence, QWidget*)
    METHOD_(QShortcut, setEnabled)
    METHOD_(QShortcut, isEnabled)
    METHOD_(QShortcut, setKey)
    METHOD_(QShortcut, key)
    SIGNAL_(QShortcut, activated)
    SIGNAL_(QShortcut, activatedAmbiguously)
    END_CLASS()

    BEGIN_CLASS(QTimer)
    METHOD_OVERLOAD(QTimer, start, void(QTimer::*)(int))
    METHOD_(QTimer, stop)
    METHOD_OVERLOAD(QTimer, setInterval, void(QTimer::*)(int))
    END_CLASS()

    BEGIN_CLASS(QStackedWidget)
    METHOD_(QStackedWidget, addWidget)
    METHOD_(QStackedWidget, setCurrentIndex)
    METHOD_(QStackedWidget, currentIndex)
    END_CLASS()

    BEGIN_CLASS(QPilsDelayedDestroy)
    CONSTRUCTOR_NOARGS(QPilsDelayedDestroy)
    END_CLASS()

    BEGIN_CLASS(QClangTranslationUnit)
    CONSTRUCTOR_NOARGS(QClangTranslationUnit)
    EXACT_METHOD(QClangTranslationUnit, parse)
    EXACT_METHOD(QClangTranslationUnit, cursor)
    END_CLASS()

    BEGIN_CLASS(QClangCursor)
    EXACT_METHOD(QClangCursor, spelling)
    EXACT_METHOD(QClangCursor, kind)
    EXACT_METHOD(QClangCursor, isNull)
    // EXACT_METHOD(QClangCursor, parentCursor)
    EXACT_METHOD(QClangCursor, firstChild)
    EXACT_METHOD(QClangCursor, nextSibling)
    END_CLASS()
}

template<typename EventT>
void qtEventDispatch(QEvent *event,
                     const QtObjectWrapper *wrapper,
                     const QtEventCliche *c)
{
    auto *e = static_cast<EventT*>(event);
    wrapper->pilsEventCallback(c, QtWrap::wrap(*e));
}

#define REGISTER_QT_EVENT(TYPE, EVENTTYPE) \
    new QtEventCliche(QEvent::TYPE, #TYPE, &qtEventDispatch<EVENTTYPE>);

    void QtEventCliche::initialize()
    {
        REGISTER_QT_EVENT(MouseMove, QMouseEvent)
        REGISTER_QT_EVENT(MouseButtonPress, QMouseEvent)
        REGISTER_QT_EVENT(MouseButtonRelease, QMouseEvent)
        REGISTER_QT_EVENT(KeyPress, QKeyEvent)
        REGISTER_QT_EVENT(KeyRelease, QKeyEvent)
        REGISTER_QT_EVENT(Resize, QResizeEvent)
        REGISTER_QT_EVENT(Wheel, QWheelEvent)
        REGISTER_QT_EVENT(FocusIn, QFocusEvent);
        REGISTER_QT_EVENT(FocusOut, QFocusEvent)
        REGISTER_QT_EVENT(Enter, QEvent)
        REGISTER_QT_EVENT(Leave, QEvent)
        REGISTER_QT_EVENT(Close, QCloseEvent)
    }
}
