; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7C5AF06B-25BE-4EAF-8BE5-FBACDF8558DA}
AppName=PILS.pils
AppVerName=PILS with juce-bindings, v. 0.4.0
AppPublisher=Ole Nielsby
AppPublisherURL=http://www.pils.org/
AppSupportURL=http://www.pils.org/
AppUpdatesURL=http://www.pils.org/
DefaultDirName={pf}\PILS.pils
DefaultGroupName=PILS
AllowNoIcons=yes
OutputDir=..\..\..\bin\win32
OutputBaseFilename=pils0.4.0_win32setup
Compression=lzma
SolidCompression=yes
ShowLanguageDialog=yes
TimestampsInUTC=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "..\..\..\readme\english\license.txt"; InfoBeforeFile: "..\..\..\readme\english\support.txt"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"; LicenseFile: "..\..\..\readme\danish\license.txt"; InfoBeforeFile: "..\..\..\readme\danish\support.txt"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\..\bin\win32\pils.exe"; DestDir: "{app}\bin\win32\"; Flags: ignoreversion
Source: "..\..\..\pils\english\system\*"; DestDir: "{app}\pils\english\system\"; Excludes: "test.pils,plumming-generator.pils,applet-plumming-generator.pils"; Flags: ignoreversion recursesubdirs
Source: "..\..\..\pils\english\compute\*"; DestDir: "{app}\pils\english\compute\"; Flags: ignoreversion recursesubdirs
Source: "..\..\..\pils\english\parse\*"; DestDir: "{app}\pils\english\parse\"; Flags: ignoreversion recursesubdirs
Source: "..\..\..\doc\html\english\*"; DestDir: "{app}\doc\html\english\"; Flags: ignoreversion
Source: "..\..\..\readme\english\*"; DestDir: "{app}\readme\english\"; Flags: ignoreversion

Source: "..\..\..\pils\danish\system\*"; DestDir: "{app}\pils\danish\system\"; Flags: ignoreversion recursesubdirs; Components: language/danish
Source: "..\..\..\doc\html\danish\*"; DestDir: "{app}\doc\html\danish\"; Flags: ignoreversion; Components: language/danish
Source: "..\..\..\readme\danish\*"; DestDir: "{app}\readme\danish\"; Flags: ignoreversion

Source: "..\..\..\pils\english\codecomb\*"; DestDir: "{app}\pils\english\codecomb\"; Flags: ignoreversion recursesubdirs; Components: codecomb

Source: "..\..\..\src\jpils\*"; DestDir: "{app}\src\jpils\"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\src\pils-kernel\*"; DestDir: "{app}\src\pils-kernel\"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\src\pilsplug\*"; DestDir: "{app}\src\pilsplug\"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\src\scripts\*"; DestDir: "{app}\src\scripts\"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\build\Win32\InnoSetup\*"; DestDir: "{app}\build\Win32\InnoSetup"; Flags: ignoreversion; Components: src
Source: "..\..\..\build\Win32\vc9\*"; DestDir: "{app}\build\Win32\vc9"; Excludes: "*.user,*.ncb,*.sdf"; Flags: ignoreversion; Components: src
Source: "..\..\..\doc\openoffice\*"; DestDir: "{app}\doc\openoffice"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\doc\scripts\*"; DestDir: "{app}\doc\scripts"; Flags: ignoreversion recursesubdirs; Components: src
Source: "..\..\..\pils\english\system\juce\plumming-generator.pils"; DestDir: "{app}\pils\english\system\juce"; Flags: ignoreversion; Components: src
; Source: "..\..\..\pils\english\system\juce\applet-plumming-generator.pils"; DestDir: "{app}\pils\english\system\juce"; Flags: ignoreversion; Components: src
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
Type: files; Name: "{app}\pils\english\system\test.pils"

[Icons]
Name: "{group}\PILS"; Filename: "{app}\bin\win32\pils.exe"
Name: "{group}\English PILS language reference"; Filename: "{app}\doc\html\english\The PILS language.html"
Name: "{group}\Dansk PILS manual"; Filename: "{app}\doc\html\danish\PILS sproget.html"; Components: language/danish
Name: "{group}\{cm:UninstallProgram,PILS}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\PILS"; Filename: "{app}\bin\win32\pils.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\PILS"; Filename: "{app}\bin\win32\pils.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\bin\win32\pils.exe"; Description: "{cm:LaunchProgram,PILS}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCR; Subkey: ".pils"; ValueType: string; ValueData: "PILS.pils"; Flags: uninsdeletekey
Root: HKCR; Subkey: ".pils\ShellNew"; ValueType: string; ValueName: "NullFile"; ValueData: " "; Flags: uninsdeletekey
Root: HKCR; Subkey: "PILS.pils"; ValueType: string; ValueData: "Pils file"; Flags: uninsdeletekey
Root: HKCR; Subkey: "PILS.pils\DefaultIcon"; ValueType: string; ValueData: """{app}\bin\win32\pils.exe"",1"
Root: HKCR; Subkey: "PILS.pils\Shell\edit\command"; ValueType: string; ValueData: """{app}\bin\win32\pils.exe"" -edit ""%1"""
Root: HKCR; Subkey: "PILS.pils\Shell\open\command"; ValueType: string; ValueData: """{app}\bin\win32\pils.exe"" ""%1"""
Root: HKCR; Subkey: "PILS.pils\Shell\register\command"; ValueType: string; ValueData: """{app}\bin\win32\pils.exe"" -register ""%1"""

[Types]
Name: "full"; Description: "Full installation"
Name: "compact"; Description: "Compact installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "main"; Description: "Main Files"; Types: full compact custom; Flags: fixed
Name: "language"; Description: "Language packs"; Types: full
Name: "language/danish"; Description: "Danish"; Types: full
Name: "codecomb"; Description: "Codecomb utilities"; Types: full
Name: "src"; Description: "C++ Source files and build scripts"; Types: full
